const CFG=window.SIMPLEPOS_CONFIG,SB=CFG.supabaseUrl,KEY=CFG.supabasePublishableKey,API=`${SB}/rest/v1`,AUTH=`${SB}/auth/v1`;
const TAX={gst:.05,qst:.09975};
let session=JSON.parse(localStorage.getItem('simplepos-session')||'null'),user=null,restaurant=null,settings=null,tables=[],products=[],orders=[],orderItems=[],invoices=[],printers=[],activeOrder=null,selectedIds=new Set(),activeCategory='TOUS',splitTarget=null,liveTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],round2=n=>Math.round((Number(n||0)+Number.EPSILON)*100)/100,money=n=>Number(n||0).toLocaleString('fr-CA',{style:'currency',currency:'CAD'}),uid=()=>crypto.randomUUID();
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(m,t='ok'){const e=$('#toast');e.textContent=m;e.dataset.type=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2500)}
function authHeaders(extra={}){return{apikey:KEY,Authorization:`Bearer ${session?.access_token||KEY}`,'Content-Type':'application/json',...extra}}
async function authRequest(path,body){const r=await fetch(`${AUTH}${path}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.error_description||d.message||'Erreur de connexion');return d}
async function rest(path,{method='GET',body,prefer='return=representation'}={}){if(!session?.access_token)throw new Error('Non connecté');const r=await fetch(`${API}/${path}`,{method,headers:authHeaders(prefer?{Prefer:prefer}:{}),body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401&&session?.refresh_token){session=await authRequest('/token?grant_type=refresh_token',{refresh_token:session.refresh_token});localStorage.setItem('simplepos-session',JSON.stringify(session));return rest(path,{method,body,prefer})}const tx=await r.text(),d=tx?JSON.parse(tx):null;if(!r.ok)throw new Error(d?.message||d?.hint||d?.details||`Supabase ${r.status}`);return d}
async function login(email,password){session=await authRequest('/token?grant_type=password',{email,password});localStorage.setItem('simplepos-session',JSON.stringify(session));await boot()}
async function signup(email,password){session=await authRequest('/signup',{email,password});if(!session.access_token)throw new Error('Compte créé. Confirme le courriel puis connecte-toi.');localStorage.setItem('simplepos-session',JSON.stringify(session));await boot()}
function logout(){localStorage.removeItem('simplepos-session');session=null;clearInterval(liveTimer);$('#app').classList.add('hidden');$('#authScreen').classList.remove('hidden')}
async function ensureRestaurant(){user=session.user;const mine=await rest('restaurants?select=*&order=created_at.asc&limit=1');if(mine.length){restaurant=mine[0];return}restaurant=(await rest('restaurants',{method:'POST',body:{name:'Mon restaurant',owner_id:user.id}}))[0];const rid=restaurant.id;await rest('app_settings',{method:'POST',body:{restaurant_id:rid}});await rest('restaurant_tables',{method:'POST',body:[1,2,3,4,5,6,7,8].map((number,i)=>({restaurant_id:rid,number,sort_order:i}))})}
async function loadAll(silent=false){if(!restaurant)return;const rid=restaurant.id;try{const[t,p,o,oi,inv,pr,as]=await Promise.all([rest(`restaurant_tables?restaurant_id=eq.${rid}&active=eq.true&select=*&order=sort_order.asc,number.asc`),rest(`products?restaurant_id=eq.${rid}&active=eq.true&select=*&order=category.asc,sort_order.asc,name.asc`),rest(`orders?restaurant_id=eq.${rid}&status=in.(open,partially_paid)&select=*&order=opened_at.asc`),rest('order_items?select=*&order=created_at.asc'),rest(`invoices?restaurant_id=eq.${rid}&select=*&order=created_at.desc&limit=100`),rest(`printers?restaurant_id=eq.${rid}&enabled=eq.true&select=*`),rest(`app_settings?restaurant_id=eq.${rid}&select=*&limit=1`)]);tables=t||[];products=p||[];orders=o||[];invoices=inv||[];printers=pr||[];settings=as?.[0]||{restaurant_id:rid,tips_enabled:true,mev_mode:'simulator'};const ids=new Set(orders.map(x=>x.id));orderItems=(oi||[]).filter(x=>ids.has(x.order_id));$('#liveDot').classList.remove('down');$('#connectionLabel').textContent='Connecté';if(!silent)renderCurrent()}catch(e){$('#liveDot').classList.add('down');$('#connectionLabel').textContent='Hors ligne';if(!silent)toast(e.message,'error')}}
async function boot(){if(!session?.access_token)return;try{await ensureRestaurant();await loadAll(true);$('#restaurantName').textContent=restaurant.name;$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');show('tablesScreen');clearInterval(liveTimer);liveTimer=setInterval(()=>loadAll(true).then(renderCurrent),5000)}catch(e){if(/JWT|token|401|expired/i.test(e.message))logout();else $('#authError').textContent=e.message}}
function calcTax(sub){const gst=round2(sub*Number(settings?.tax_gst??TAX.gst)),qst=round2(sub*Number(settings?.tax_qst??TAX.qst));return{gst,qst,total:round2(sub+gst+qst)}}
function mevInvoiceStatus(s){return s==='accepted'?'accepted':['retryable','timeout','network_error','pending','sending'].includes(s)?'retryable':s==='rejected'?'rejected':'failed'}
function companyHeaderLines(){const r=restaurant||{};const addr=[r.address,[r.city,r.postal_code].filter(Boolean).join(' ')].filter(Boolean).join(', ');return[r.legal_name||r.name,r.phone||null,addr||null,r.gst_number?`TPS ${r.gst_number}`:null,r.qst_number?`TVQ ${r.qst_number}`:null].filter(Boolean).join('\n')}
const openOrder=tableId=>orders.find(o=>o.table_id===tableId&&['open','partially_paid'].includes(o.status));
const itemsFor=orderId=>orderItems.filter(i=>i.order_id===orderId&&i.kitchen_status!=='cancelled'&&Number(i.paid_quantity||0)<Number(i.quantity||1));
const orderSubtotal=orderId=>round2(itemsFor(orderId).reduce((s,i)=>s+Number(i.unit_price)*(Number(i.quantity)-Number(i.paid_quantity||0)),0));
function show(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===id));renderCurrent()}
function renderCurrent(){const s=$('.screen.active')?.id;if(s==='tablesScreen')renderTables();if(s==='orderScreen')renderOrder();if(s==='payScreen')renderPay();if(s==='historyScreen')renderHistory();if(s==='settingsScreen')renderSettings()}
function renderTables(){$('#pageContext').textContent='';$('#tablesGrid').innerHTML=tables.map(t=>{const o=openOrder(t.id),sub=o?orderSubtotal(o.id):0,tx=calcTax(sub),age=o?Math.max(1,Math.floor((Date.now()-new Date(o.opened_at))/60000)):0;return`<button class="table-card ${o?'occupied':''}" data-table="${t.id}"><div class="table-card-top"><strong>${esc(t.label||`Table ${t.number}`)}</strong><span>${o?`${age} min`:'Libre'}</span></div>${o?`<div class="table-total">${money(tx.total)}</div><div class="table-meta">${o.guest_count} client${o.guest_count>1?'s':''} · ${itemsFor(o.id).length} article${itemsFor(o.id).length>1?'s':''}</div>`:'<div class="table-empty">Ouvrir la table</div>'}</button>`}).join('');$$('[data-table]').forEach(b=>b.onclick=()=>openTable(b.dataset.table))}
async function openTable(tableId){let o=openOrder(tableId);if(!o){o=(await rest('orders',{method:'POST',body:{restaurant_id:restaurant.id,table_id:tableId,guest_count:1,created_by:user.id,status:'open'}}))[0];orders.push(o)}activeOrder=o;selectedIds.clear();splitTarget=null;show('orderScreen')}
function renderCategories(){const cats=['TOUS',...new Set(products.map(p=>p.category||'AUTRES'))];if(!cats.includes(activeCategory))activeCategory='TOUS';$('#categories').innerHTML=cats.map(c=>`<button class="category-tab ${c===activeCategory?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderOrder()})}
function totalsHtml(sub,gst,qst,total,tip=0,paymentTotal=null){return`<div class="total-line"><span>Sous-total</span><span>${money(sub)}</span></div><div class="total-line minor"><span>TPS</span><span>${money(gst)}</span></div><div class="total-line minor"><span>TVQ</span><span>${money(qst)}</span></div>${tip?`<div class="total-line"><span>Pourboire</span><span>${money(tip)}</span></div>`:''}<div class="total-line grand"><span>Total</span><span>${money(paymentTotal??total)}</span></div>`}
function renderOrder(){if(!activeOrder)return show('tablesScreen');const table=tables.find(t=>t.id===activeOrder.table_id);$('#pageContext').textContent=` · ${table.label||`Table ${table.number}`}`;$('#orderTableLabel').textContent=table.label||`Table ${table.number}`;$('#guestButton').textContent=`${activeOrder.guest_count} client${activeOrder.guest_count>1?'s':''}`;renderCategories();const list=activeCategory==='TOUS'?products:products.filter(p=>(p.category||'AUTRES')===activeCategory);$('#products').innerHTML=list.map(p=>`<button class="product-card" data-product="${p.id}"><span>${esc(p.name)}</span><strong>${money(p.price)}</strong></button>`).join('')||'<div class="empty-state">Menu vide. Ajoutez des articles dans Réglages.</div>';$$('[data-product]').forEach(b=>b.onclick=()=>addProduct(b.dataset.product));const items=itemsFor(activeOrder.id);$('#ticketTitle').textContent='Commande';$('#ticketMeta').textContent=`${items.length} article${items.length!==1?'s':''}`;$('#ticketList').innerHTML=items.map(i=>`<div class="ticket-row"><div><strong>${esc(i.name)}</strong><span class="item-state ${i.kitchen_status}">${i.kitchen_status==='sent'?'Envoyé':'Nouveau'}</span></div><span>${money(i.unit_price)}</span><button class="icon-btn" data-remove="${i.id}">×</button></div>`).join('')||'<div class="empty-state small-empty">Touchez un article pour commencer.</div>';$$('[data-remove]').forEach(b=>b.onclick=()=>removeItem(b.dataset.remove));const sub=orderSubtotal(activeOrder.id),tx=calcTax(sub);$('#ticketTotals').innerHTML=totalsHtml(sub,tx.gst,tx.qst,tx.total)}
async function addProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const d=(await rest('order_items',{method:'POST',body:{order_id:activeOrder.id,product_id:p.id,name:p.name,unit_price:p.price,quantity:1,paid_quantity:0,kitchen_status:'new'}}))[0];orderItems.push(d);renderOrder()}
async function removeItem(id){const i=orderItems.find(x=>x.id===id);if(!i)return;if(i.kitchen_status==='sent'&&!confirm('Article déjà envoyé. L’annuler?'))return;await rest(`order_items?id=eq.${id}`,{method:'PATCH',body:{kitchen_status:'cancelled'}});i.kitchen_status='cancelled';renderOrder()}
async function updateGuests(){const n=Number(prompt('Nombre de clients',activeOrder.guest_count));if(!Number.isInteger(n)||n<1)return;await rest(`orders?id=eq.${activeOrder.id}`,{method:'PATCH',body:{guest_count:n,updated_at:new Date().toISOString()}});activeOrder.guest_count=n;renderOrder()}
const printer=role=>printers.find(p=>p.role===role&&p.enabled);
async function savePrinter(role,ip){const p=printer(role);if(p){const d=(await rest(`printers?id=eq.${p.id}`,{method:'PATCH',body:{ip_address:ip,port:9100,enabled:!!ip}}))[0];Object.assign(p,d)}else if(ip)printers.push((await rest('printers',{method:'POST',body:{restaurant_id:restaurant.id,name:role==='kitchen'?'Cuisine':'Reçu',role,ip_address:ip,port:9100,enabled:true}}))[0])}
async function printText(text,role){const p=printer(role);if(!p?.ip_address)throw new Error(`IP imprimante ${role==='kitchen'?'cuisine':'reçu'} manquante`);const r=await fetch('/print',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:p.ip_address,port:p.port||9100,text,cut:true})});if(!r.ok)throw new Error('Imprimante inaccessible');return r.json()}
async function sendKitchen(){const items=itemsFor(activeOrder.id).filter(i=>i.kitchen_status==='new');if(!items.length)return toast('Rien de nouveau');const table=tables.find(t=>t.id===activeOrder.table_id),ticket=`CUISINE\n${table.label||`Table ${table.number}`}\n${items.map(i=>`1 x ${i.name}`).join('\n')}\n`;try{await printText(ticket,'kitchen')}catch(e){if(!confirm(`${e.message}. Marquer envoyé quand même?`))return}await Promise.all(items.map(i=>rest(`order_items?id=eq.${i.id}`,{method:'PATCH',body:{kitchen_status:'sent',kitchen_sent_at:new Date().toISOString()}})));items.forEach(i=>i.kitchen_status='sent');renderOrder();toast('Envoyé en cuisine')}
function selectedItems(){const all=itemsFor(activeOrder.id);return selectedIds.size?all.filter(i=>selectedIds.has(i.id)):all}
function selectedSubtotal(){return round2(selectedItems().reduce((s,i)=>s+Number(i.unit_price)*(Number(i.quantity)-Number(i.paid_quantity||0)),0))}
function selectedGross(){return calcTax(selectedSubtotal()).total}
function currentDue(){const full=selectedGross();return splitTarget&&splitTarget<full?splitTarget:full}
function renderPay(){if(!activeOrder)return show('tablesScreen');const table=tables.find(t=>t.id===activeOrder.table_id),items=itemsFor(activeOrder.id);$('#payTableLabel').textContent=table.label||`Table ${table.number}`;selectedIds=new Set([...selectedIds].filter(id=>items.some(i=>i.id===id)));$('#payItems').innerHTML=items.map(i=>`<button class="pay-row ${selectedIds.has(i.id)?'selected':''}" data-payitem="${i.id}"><span class="check">${selectedIds.has(i.id)?'✓':''}</span><span>${esc(i.name)}</span><strong>${money(i.unit_price)}</strong></button>`).join('');$$('[data-payitem]').forEach(b=>b.onclick=()=>{selectedIds.has(b.dataset.payitem)?selectedIds.delete(b.dataset.payitem):selectedIds.add(b.dataset.payitem);splitTarget=null;renderPay()});renderPaySummary()}
function renderPaySummary(){const sub=selectedSubtotal(),tx=calcTax(sub),due=currentDue();$('#selectedSummary').innerHTML=selectedIds.size?`<div class="selection-note">${selectedIds.size} article${selectedIds.size>1?'s':''} sélectionné${selectedIds.size>1?'s':''}</div>`:'<div class="selection-note">Solde complet</div>';$('#payTotals').innerHTML=totalsHtml(sub,tx.gst,tx.qst,tx.total,0,due);$('#baseDue').textContent=money(due);updateTerminalPreview();updateCashPreview()}
function splitAmounts(total,n){const cents=Math.round(total*100),base=Math.floor(cents/n),rem=cents-base*n;return Array.from({length:n},(_,i)=>(base+(i>=n-rem?1:0))/100)}
function renderSplit(n){if(!Number.isInteger(n)||n<2||n>30){splitTarget=null;$('#splitBox').innerHTML='';renderPaySummary();return}const parts=splitAmounts(selectedGross(),n);splitTarget=parts[0];$('#splitBox').innerHTML=`<div class="split-preview">${parts.map((p,i)=>`<div><span>Part ${i+1}</span><strong>${money(p)}</strong></div>`).join('')}</div>`;renderPaySummary()}
function updateTerminalPreview(){const due=currentDue(),v=Number($('#terminalTotal')?.value||0),tip=settings?.tips_enabled&&v>=due?round2(v-due):0;$('#terminalTip').textContent=v?`Pourboire détecté : ${money(tip)}`:'Entrez le total affiché sur le terminal.'}
function updateCashPreview(){const due=currentDue(),received=Number($('#cashReceived')?.value||0),tip=settings?.tips_enabled?Math.max(0,Number($('#cashTip')?.value||0)):0,change=round2(received-due-tip);$('#cashChange').textContent=received?`Monnaie : ${money(Math.max(0,change))}`:'Entrez le montant reçu.'}
async function submitMev(invoice){if(settings?.mev_mode==='disabled')return{environment:'DISABLED',status:'disabled',certified:false};if(settings?.mev_mode==='live')throw new Error('MEV production verrouillé : certificats officiels requis.');const r=await fetch(CFG.mevSimulatorUrl,{method:'POST',headers:authHeaders(),body:JSON.stringify(invoice)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`MEV simulateur ${r.status}`);return d}
function allocationForDue(due){const fullGross=selectedGross(),subAll=selectedSubtotal();if(Math.abs(due-fullGross)<.011)return{sub:subAll,tax:calcTax(subAll),items:selectedItems(),kind:'items'};const ratio=due/fullGross,sub=round2(subAll*ratio),tax=calcTax(sub);tax.total=due;return{sub,tax,items:[],kind:'amount'}}
async function payCard(){const due=currentDue(),terminal=round2(Number($('#terminalTotal').value));if(!terminal||terminal<due-.009)return toast(`Le total terminal doit être au moins ${money(due)}`,'error');const tip=settings?.tips_enabled?round2(terminal-due):0,a=allocationForDue(due);await finalizeInvoice({...a,method:'card',tipAmount:tip,paymentTotal:terminal,tenderedAmount:terminal,changeDue:0,tipSource:tip?'external_terminal':'none',allocation:splitTarget?{amount:due,split:true}:null})}
async function payCash(){const due=currentDue(),received=round2(Number($('#cashReceived').value)),tip=settings?.tips_enabled?round2(Number($('#cashTip').value||0)):0;if(!received||received<due+tip-.009)return toast(`Montant reçu insuffisant`,'error');const change=round2(received-due-tip),a=allocationForDue(due);await finalizeInvoice({...a,method:'cash',tipAmount:tip,paymentTotal:round2(due+tip),tenderedAmount:received,changeDue:change,tipSource:tip?'manual_cash':'none',allocation:splitTarget?{amount:due,split:true}:null})}
async function payOther(){const due=currentDue(),a=allocationForDue(due);await finalizeInvoice({...a,method:'other',tipAmount:0,paymentTotal:due,tenderedAmount:due,changeDue:0,tipSource:'none',allocation:splitTarget?{amount:due,split:true}:null})}
async function finalizeInvoice({items,sub,tax,method,tipAmount,paymentTotal,tenderedAmount,changeDue,tipSource,kind,allocation}){const inv=(await rest('invoices',{method:'POST',body:{id:uid(),restaurant_id:restaurant.id,order_id:activeOrder.id,subtotal:sub,gst:tax.gst,qst:tax.qst,total:tax.total,tip_amount:tipAmount,payment_total:paymentTotal,tip_mode:tipSource,tip_value:tipAmount,status:'pending_mev',mev_payload:{kind,allocation:allocation||null}}}))[0];if(items.length)await rest('invoice_items',{method:'POST',body:items.map(i=>({invoice_id:inv.id,order_item_id:i.id,quantity:Number(i.quantity)-Number(i.paid_quantity||0),unit_price:i.unit_price,line_total:round2(Number(i.unit_price)*(Number(i.quantity)-Number(i.paid_quantity||0)))}))});await rest('payments',{method:'POST',body:{restaurant_id:restaurant.id,invoice_id:inv.id,method,amount:paymentTotal,tip_amount:tipAmount,tendered_amount:tenderedAmount,terminal_total:method==='card'?tenderedAmount:null,change_due:changeDue,tip_source:tipSource}});let fiscal;try{fiscal=await submitMev({id:inv.id,table_id:activeOrder.table_id,subtotal:sub,gst:tax.gst,qst:tax.qst,total:tax.total,tip:tipAmount,payment_total:paymentTotal,payment_method:method,items:items.map(i=>({name:i.name,price:i.unit_price}))});await rest('mev_attempts',{method:'POST',body:{restaurant_id:restaurant.id,invoice_id:inv.id,environment:fiscal.environment||'SIMULATOR',status:fiscal.status,request_payload:{invoice_id:inv.id,total:tax.total},response_payload:fiscal,transaction_id:fiscal.transaction_id,qr_payload:fiscal.qr_payload}})}catch(e){fiscal={environment:'SIMULATOR',status:'network_error',certified:false,error:e.message};await rest('mev_attempts',{method:'POST',body:{restaurant_id:restaurant.id,invoice_id:inv.id,environment:'simulator',status:'network_error',error_code:'NETWORK_ERROR',error_message:e.message,request_payload:{invoice_id:inv.id,total:tax.total}}})}if(items.length){await Promise.all(items.map(i=>rest(`order_items?id=eq.${i.id}`,{method:'PATCH',body:{paid_quantity:i.quantity}})));items.forEach(i=>i.paid_quantity=i.quantity)}else{applyAmount(dueWithoutTip(tax.total));await Promise.all(itemsFor(activeOrder.id).map(i=>rest(`order_items?id=eq.${i.id}`,{method:'PATCH',body:{paid_quantity:i.paid_quantity}})))}inv.mev_response=fiscal;inv.mev_transaction_id=fiscal.transaction_id;inv.status=mevInvoiceStatus(fiscal.status);invoices.unshift(inv);await updateOrderStatus();selectedIds.clear();splitTarget=null;showReceipt({...inv,method,items,fiscal,tendered_amount:tenderedAmount,change_due:changeDue})}
function dueWithoutTip(v){return Number(v||0)}
function applyAmount(grossAmount){let cents=Math.round(grossAmount*100);for(const i of itemsFor(activeOrder.id)){const gross=Math.round(calcTax(Number(i.unit_price)*(Number(i.quantity)-Number(i.paid_quantity||0))).total*100);if(cents>=gross){i.paid_quantity=i.quantity;cents-=gross}else if(cents>0){const remainingQty=Number(i.quantity)-Number(i.paid_quantity||0),fraction=cents/gross;i.paid_quantity=round2(Number(i.paid_quantity||0)+fraction*remainingQty);cents=0;break}}}
async function updateOrderStatus(){const left=itemsFor(activeOrder.id);const status=left.length?'partially_paid':'closed';await rest(`orders?id=eq.${activeOrder.id}`,{method:'PATCH',body:{status,closed_at:status==='closed'?new Date().toISOString():null,updated_at:new Date().toISOString()}});if(status==='closed'){orders=orders.filter(o=>o.id!==activeOrder.id);activeOrder=null}}
function showReceipt(inv){const f=inv.fiscal||inv.mev_response||{},rows=(inv.items||[]).map(i=>`<div class="receipt-line"><span>${esc(i.name)}</span><span>${money(i.unit_price||i.price)}</span></div>`).join('');openModal(`<div class="receipt-modal"><div class="modal-title-row"><div><span class="eyebrow">Facture</span><h2>${f.status==='accepted'?'Paiement accepté':'Paiement enregistré'}</h2></div><button class="icon-btn" data-close>×</button></div><div class="receipt-paper"><strong>${esc(restaurant.name)}</strong><div class="receipt-muted">${new Date().toLocaleString('fr-CA')}</div><hr>${rows||'<div class="receipt-muted">Paiement partiel</div>'}<hr>${totalsHtml(inv.subtotal,inv.gst,inv.qst,inv.total,inv.tip_amount,inv.payment_total)}${inv.change_due?`<div class="receipt-line"><span>Monnaie</span><span>${money(inv.change_due)}</span></div>`:''}<div class="receipt-fiscal"><span>MEV</span><strong>${esc(f.transaction_id||f.status||'Non transmis')}</strong><small>${f.certified===false?'SIMULATION — NON CERTIFIÉ':''}</small><code>${esc(f.qr_payload||'')}</code></div></div><div class="button-row"><button id="modalPrint" class="btn primary">Imprimer</button><button class="btn" data-close>Fermer</button></div></div>`);$('#modalPrint').onclick=()=>printReceipt(inv).catch(e=>toast(e.message,'error'))}
async function printReceipt(inv){const f=inv.fiscal||inv.mev_response||{};await printText(`${companyHeaderLines()}\nPAIEMENT REÇU\nFacture ${inv.id}\nTPS ${money(inv.gst)}\nTVQ ${money(inv.qst)}\nPourboire ${money(inv.tip_amount)}\nTOTAL ${money(inv.payment_total||inv.total)}\n${inv.change_due?`Monnaie ${money(inv.change_due)}\n`:''}MEV ${f.transaction_id||f.status||''}\n${f.qr_payload||''}\n`,'receipt');toast('Reçu envoyé')}
function renderHistory(){$('#historyList').innerHTML=invoices.map(i=>`<div class="history-row"><div><strong>${new Date(i.created_at).toLocaleString('fr-CA')}</strong><span>${i.id.slice(0,8).toUpperCase()} · ${i.mev_transaction_id||'MEV en attente'}</span></div><div><strong>${money(i.payment_total||i.total)}</strong><span class="status-pill ${i.status}">${i.status}</span></div></div>`).join('')||'<div class="empty-state">Aucune facture.</div>'}
function renderSettings(){$('#menuAdminList').innerHTML=products.map(p=>`<div class="admin-row"><div><strong>${esc(p.name)}</strong><span>${esc(p.category||'AUTRES')} · ${money(p.price)}</span></div><button class="btn small" data-edit-product="${p.id}">Modifier</button></div>`).join('')||'<div class="empty-state">Menu vide.</div>';$$('[data-edit-product]').forEach(b=>b.onclick=()=>productModal(products.find(p=>p.id===b.dataset.editProduct)));$('#tipsEnabled').checked=!!settings?.tips_enabled;$('#kitchenIp').value=printer('kitchen')?.ip_address||'';$('#receiptIp').value=printer('receipt')?.ip_address||'';$('#mevMode').value=settings?.mev_mode||'simulator';$('#companyLegalName').value=restaurant.legal_name||'';$('#companyAddress').value=restaurant.address||'';$('#companyCity').value=restaurant.city||'';$('#companyPostalCode').value=restaurant.postal_code||'';$('#companyPhone').value=restaurant.phone||'';$('#companyGst').value=restaurant.gst_number||'';$('#companyQst').value=restaurant.qst_number||'';const isOwner=user?.id===restaurant.owner_id;$$('#companySettings input').forEach(i=>i.disabled=!isOwner);$('#saveCompanyInfo').disabled=!isOwner;$('#companyOwnerNote').textContent=isOwner?"Renseignements exigés sur les factures et reçus (guide SW-76).":"Seul le ou la propriétaire du compte peut modifier ces informations."}
async function saveCompanyInfo(){const body={legal_name:$('#companyLegalName').value.trim()||null,address:$('#companyAddress').value.trim()||null,city:$('#companyCity').value.trim()||null,postal_code:$('#companyPostalCode').value.trim()||null,phone:$('#companyPhone').value.trim()||null,gst_number:$('#companyGst').value.trim()||null,qst_number:$('#companyQst').value.trim()||null};const d=(await rest(`restaurants?id=eq.${restaurant.id}`,{method:'PATCH',body}))[0];Object.assign(restaurant,d);toast('Coordonnées enregistrées')}
function productModal(p=null){openModal(`<form id="productForm"><div class="modal-title-row"><div><span class="eyebrow">Menu</span><h2>${p?'Modifier':'Nouvel'} article</h2></div><button type="button" class="icon-btn" data-close>×</button></div><label>Nom<input id="pName" required value="${esc(p?.name||'')}"></label><div class="form-two"><label>Prix<input id="pPrice" type="number" min="0" step="0.01" required value="${p?.price??''}"></label><label>Catégorie<input id="pCategory" required value="${esc(p?.category||'PLATS')}"></label></div><label>Station<select id="pStation"><option value="kitchen">Cuisine</option><option value="bar">Bar</option><option value="none">Aucune</option></select></label><div class="button-row"><button class="btn primary">Enregistrer</button>${p?'<button type="button" class="btn danger" id="deleteProduct">Désactiver</button>':''}</div></form>`);$('#pStation').value=p?.kitchen_station||'kitchen';$('#productForm').onsubmit=async e=>{e.preventDefault();const body={restaurant_id:restaurant.id,name:$('#pName').value.trim(),price:Number($('#pPrice').value),category:$('#pCategory').value.trim().toUpperCase(),kitchen_station:$('#pStation').value,updated_at:new Date().toISOString()};if(p)Object.assign(p,(await rest(`products?id=eq.${p.id}`,{method:'PATCH',body}))[0]);else products.push((await rest('products',{method:'POST',body}))[0]);closeModal();renderSettings();toast('Menu enregistré')};if(p)$('#deleteProduct').onclick=async()=>{if(!confirm('Désactiver cet article?'))return;await rest(`products?id=eq.${p.id}`,{method:'PATCH',body:{active:false}});products=products.filter(x=>x.id!==p.id);closeModal();renderSettings()}}
async function saveSettings(){const d=(await rest(`app_settings?restaurant_id=eq.${restaurant.id}`,{method:'PATCH',body:{tips_enabled:$('#tipsEnabled').checked,mev_mode:$('#mevMode').value,updated_at:new Date().toISOString()}}))[0];settings={...settings,...d};toast('Réglages enregistrés')}
async function addTable(){const n=Number(prompt('Numéro de table'));if(!Number.isInteger(n)||n<1)return;try{tables.push((await rest('restaurant_tables',{method:'POST',body:{restaurant_id:restaurant.id,number:n,sort_order:tables.length}}))[0]);renderTables()}catch(e){toast(e.message,'error')}}
function openModal(html){$('#modalCard').innerHTML=html;$('#modal').classList.add('show');$$('[data-close]').forEach(b=>b.onclick=closeModal)}function closeModal(){$('#modal').classList.remove('show');$('#modalCard').innerHTML=''}
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';try{await login($('#authEmail').value.trim(),$('#authPassword').value)}catch(err){$('#authError').textContent=err.message}};$('#signupBtn').onclick=async()=>{try{await signup($('#authEmail').value.trim(),$('#authPassword').value)}catch(err){$('#authError').textContent=err.message}};$('#logoutBtn').onclick=logout;$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));$('#newTableBtn').onclick=addTable;$('#guestButton').onclick=updateGuests;$('#sendKitchen').onclick=sendKitchen;$('#printAddition').onclick=async()=>{const table=tables.find(t=>t.id===activeOrder.table_id),sub=orderSubtotal(activeOrder.id),tx=calcTax(sub);try{await printText(`${companyHeaderLines()}\nFACTURE ORIGINALE\n${table.label||`Table ${table.number}`}\n${itemsFor(activeOrder.id).map(i=>`${i.name} ${money(i.unit_price)}`).join('\n')}\nTOTAL ${money(tx.total)}\n`,'receipt');toast('Addition imprimée')}catch(e){toast(e.message,'error')}};$('#goPay').onclick=()=>{selectedIds.clear();splitTarget=null;show('payScreen')};$$('[data-split]').forEach(b=>b.onclick=()=>renderSplit(Number(b.dataset.split)));$('#customSplit').oninput=e=>renderSplit(Number(e.target.value));$('#terminalTotal').oninput=updateTerminalPreview;$('#cashReceived').oninput=updateCashPreview;$('#cashTip').oninput=updateCashPreview;$('#payCardBtn').onclick=()=>payCard().catch(e=>toast(e.message,'error'));$('#payCashBtn').onclick=()=>payCash().catch(e=>toast(e.message,'error'));$('#payOtherBtn').onclick=()=>payOther().catch(e=>toast(e.message,'error'));$('#newProductBtn').onclick=()=>productModal();$('#tipsEnabled').onchange=saveSettings;$('#mevMode').onchange=saveSettings;$('#saveCompanyInfo').onclick=()=>saveCompanyInfo().catch(e=>toast(e.message,'error'));$('#savePrinters').onclick=async()=>{try{await savePrinter('kitchen',$('#kitchenIp').value.trim());await savePrinter('receipt',$('#receiptIp').value.trim());toast('Imprimantes enregistrées')}catch(e){toast(e.message,'error')}};$('#testKitchen').onclick=()=>printText('TEST CUISINE\nSimplePOS\n','kitchen').then(()=>toast('Test envoyé')).catch(e=>toast(e.message,'error'));$('#testReceipt').onclick=()=>printText('TEST RECU\nSimplePOS\n','receipt').then(()=>toast('Test envoyé')).catch(e=>toast(e.message,'error'));$('#refreshHistory').onclick=()=>loadAll().then(renderHistory);$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'}),1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(session?.access_token)boot();