import{submitMevTransaction,flushMevQueue,submitMevUserReport}from'./mev-live.js';
import{datTrans}from'./mev-protocol.js';
const CFG=window.RESTO360_CONFIG,SB=CFG.supabaseUrl,KEY=CFG.supabasePublishableKey,API=`${SB}/rest/v1`,AUTH=`${SB}/auth/v1`;
const TAX={gst:.05,qst:.09975};
let session=JSON.parse(localStorage.getItem('resto360-session')||'null'),user=null,restaurant=null,settings=null,tables=[],products=[],orders=[],orderItems=[],invoices=[],printers=[],activeOrder=null,selectedIds=new Set(),activeCategory='TOUS',splitTarget=null,liveTimer=null,cardType='credit';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],round2=n=>Math.round((Number(n||0)+Number.EPSILON)*100)/100,money=n=>Number(n||0).toLocaleString('fr-CA',{style:'currency',currency:'CAD'}),uid=()=>crypto.randomUUID();
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(m,t='ok'){const e=$('#toast');e.textContent=m;e.dataset.type=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2500)}
function authHeaders(extra={}){return{apikey:KEY,Authorization:`Bearer ${session?.access_token||KEY}`,'Content-Type':'application/json',...extra}}
async function authRequest(path,body){const r=await fetch(`${AUTH}${path}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.error_description||d.message||'Erreur de connexion');return d}
async function rest(path,{method='GET',body,prefer='return=representation'}={}){if(!session?.access_token)throw new Error('Non connecté');const r=await fetch(`${API}/${path}`,{method,headers:authHeaders(prefer?{Prefer:prefer}:{}),body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401&&session?.refresh_token){session=await authRequest('/token?grant_type=refresh_token',{refresh_token:session.refresh_token});localStorage.setItem('resto360-session',JSON.stringify(session));return rest(path,{method,body,prefer})}const tx=await r.text(),d=tx?JSON.parse(tx):null;if(!r.ok)throw new Error(d?.message||d?.hint||d?.details||`Supabase ${r.status}`);return d}
async function login(email,password){session=await authRequest('/token?grant_type=password',{email,password});localStorage.setItem('resto360-session',JSON.stringify(session));localStorage.setItem('resto360-login-at',new Date().toISOString());await boot()}
async function signup(email,password){session=await authRequest('/signup',{email,password});if(!session.access_token)throw new Error('Compte créé. Confirme le courriel puis connecte-toi.');localStorage.setItem('resto360-session',JSON.stringify(session));await boot()}
function logout(){localStorage.removeItem('resto360-session');session=null;clearInterval(liveTimer);$('#app').classList.add('hidden');$('#authScreen').classList.remove('hidden')}
async function ensureRestaurant(){user=session.user;const mine=await rest('restaurants?select=*&order=created_at.asc&limit=1');if(mine.length){restaurant=mine[0];return}restaurant=(await rest('restaurants',{method:'POST',body:{name:'Mon restaurant',owner_id:user.id}}))[0];const rid=restaurant.id;await rest('app_settings',{method:'POST',body:{restaurant_id:rid}});await rest('restaurant_tables',{method:'POST',body:[1,2,3,4,5,6,7,8].map((number,i)=>({restaurant_id:rid,number,sort_order:i}))})}
async function loadAll(silent=false){if(!restaurant)return;const rid=restaurant.id;try{const[t,p,o,oi,inv,pr,as]=await Promise.all([rest(`restaurant_tables?restaurant_id=eq.${rid}&active=eq.true&select=*&order=sort_order.asc,number.asc`),rest(`products?restaurant_id=eq.${rid}&active=eq.true&select=*&order=category.asc,sort_order.asc,name.asc`),rest(`orders?restaurant_id=eq.${rid}&status=in.(open,partially_paid)&select=*&order=opened_at.asc`),rest('order_items?select=*&order=created_at.asc'),rest(`invoices?restaurant_id=eq.${rid}&select=*&order=created_at.desc&limit=100`),rest(`printers?restaurant_id=eq.${rid}&enabled=eq.true&select=*`),rest(`app_settings?restaurant_id=eq.${rid}&select=*&limit=1`)]);tables=t||[];products=p||[];orders=o||[];invoices=inv||[];printers=pr||[];settings=as?.[0]||{restaurant_id:rid,tips_enabled:true,mev_mode:'simulator'};const ids=new Set(orders.map(x=>x.id));orderItems=(oi||[]).filter(x=>ids.has(x.order_id));$('#liveDot').classList.remove('down');$('#connectionLabel').textContent='Connecté';if(!silent)renderCurrent()}catch(e){$('#liveDot').classList.add('down');$('#connectionLabel').textContent='Hors ligne';if(!silent)toast(e.message,'error')}}
async function boot(){if(!session?.access_token)return;try{await ensureRestaurant();await loadAll(true);$('#restaurantName').textContent=restaurant.name;$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');show('tablesScreen');updateFormationBanner();clearInterval(liveTimer);liveTimer=setInterval(()=>loadAll(true).then(renderCurrent),5000)}catch(e){if(/JWT|token|401|expired/i.test(e.message))logout();else $('#authError').textContent=e.message}}
function calcTax(sub){const gst=round2(sub*Number(settings?.tax_gst??TAX.gst)),qst=round2(sub*Number(settings?.tax_qst??TAX.qst));return{gst,qst,total:round2(sub+gst+qst)}}
function mevInvoiceStatus(s){return s==='accepted'?'accepted':['retryable','timeout','network_error','pending','sending'].includes(s)?'retryable':s==='rejected'?'rejected':'failed'}
// Character set accepted by WEB-SRM for item and user names, per vendors already
// certified. Rejecting here avoids a rejected transmission later.
const SRM_NAME_RE=/^[a-zA-Z0-9@:!#$%&'()*+,\-.=?_|~/\\ ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÑÒÓÔÕÖØÙÚÛÜÝàáâãäåæçèéêëìíîïðñòóôõöøùúûüýÿ]+$/;
function srmNameError(name){
  const v=String(name??'');
  if(v.length<2||v.length>128)return 'Le nom doit faire entre 2 et 128 caractères.';
  if(v!==v.trim())return 'Le nom ne doit pas commencer ni finir par une espace.';
  if(!SRM_NAME_RE.test(v))return "Le nom contient un caractère refusé par le MEV-WEB (apostrophe droite ' seulement, pas d'emoji ni de crochets).";
  return null;
}
async function logFiscalEvent(event_type,extra={}){try{await rest('fiscal_events',{method:'POST',prefer:'return=minimal',body:{restaurant_id:restaurant.id,event_type,created_by:user?.id||null,...extra}})}catch{}}
// SW-76: a document produced while the MEV link is down must say so on paper.
function offlineMarker(){return navigator.onLine?null:'PROBLÈME DE COMMUNICATION'}
function companyHeaderLines(){const r=restaurant||{};const addr=[r.address,[r.city,r.postal_code].filter(Boolean).join(' ')].filter(Boolean).join(', ');return[r.legal_name||r.name,r.phone||null,addr||null,r.gst_number?`TPS ${r.gst_number}`:null,r.qst_number?`TVQ ${r.qst_number}`:null].filter(Boolean).join('\n')}
const openOrder=tableId=>orders.find(o=>o.table_id===tableId&&['open','partially_paid'].includes(o.status));
const itemsFor=orderId=>orderItems.filter(i=>i.order_id===orderId&&i.kitchen_status!=='cancelled'&&Number(i.paid_quantity||0)<Number(i.quantity||1));
const orderSubtotal=orderId=>round2(itemsFor(orderId).reduce((s,i)=>s+Number(i.unit_price)*(Number(i.quantity)-Number(i.paid_quantity||0)),0));
function show(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===id));renderCurrent()}
function renderCurrent(){const s=$('.screen.active')?.id;if(s==='tablesScreen')renderTables();if(s==='orderScreen')renderOrder();if(s==='payScreen')renderPay();if(s==='historyScreen')renderHistory();if(s==='settingsScreen')renderSettings()}
function renderTables(){$('#pageContext').textContent='';$('#tablesGrid').innerHTML=tables.map(t=>{const o=openOrder(t.id),sub=o?orderSubtotal(o.id):0,tx=calcTax(sub),age=o?Math.max(1,Math.floor((Date.now()-new Date(o.opened_at))/60000)):0;return`<button class="table-card ${o?'occupied':''}" data-table="${t.id}"><div class="table-card-top"><strong>${esc(t.label||`Table ${t.number}`)}</strong><span>${o?`${age} min`:'Libre'}</span></div>${o?`<div class="table-total">${money(tx.total)}</div><div class="table-meta">${o.guest_count} client${o.guest_count>1?'s':''} · ${itemsFor(o.id).length} article${itemsFor(o.id).length>1?'s':''}</div>`:'<div class="table-empty">Ouvrir la table</div>'}</button>`}).join('');$$('[data-table]').forEach(b=>b.onclick=()=>openTable(b.dataset.table))}
async function openTable(tableId){let o=openOrder(tableId);if(!o){o=(await rest('orders',{method:'POST',body:{restaurant_id:restaurant.id,table_id:tableId,guest_count:1,created_by:user.id,status:'open'}}))[0];orders.push(o)}activeOrder=o;selectedIds.clear();splitTarget=null;show('orderScreen')}
function renderCategories(){const cats=['TOUS',...new Set(products.map(p=>p.category||'AUTRES'))];if(!cats.includes(activeCategory))activeCategory='TOUS';$('#categories').innerHTML=cats.map(c=>`<button class="category-tab ${c===activeCategory?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderOrder()})}
function totalsHtml(sub,gst,qst,total,tip=0,paymentTotal=null){return`<div class="total-line"><span>Sous-total</span><span>${money(sub)}</span></div><div class="total-line minor"><span>TPS</span><span>${money(gst)}</span></div><div class="total-line minor"><span>TVQ</span><span>${money(qst)}</span></div>${tip?`<div class="total-line"><span>Pourboire</span><span>${money(tip)}</span></div>`:''}<div class="total-line grand"><span>Total</span><span>${money(paymentTotal??total)}</span></div>`}
function renderOrder(){if(!activeOrder)return show('tablesScreen');const table=tables.find(t=>t.id===activeOrder.table_id);$('#pageContext').textContent=` · ${table.label||`Table ${table.number}`}`;$('#orderTableLabel').textContent=table.label||`Table ${table.number}`;$('#guestButton').textContent=`${activeOrder.guest_count} client${activeOrder.guest_count>1?'s':''}`;renderCategories();const list=activeCategory==='TOUS'?products:products.filter(p=>(p.category||'AUTRES')===activeCategory);$('#products').innerHTML=list.map(p=>`<button class="product-card" data-product="${p.id}"><span>${esc(p.name)}</span><strong>${money(p.price)}</strong></button>`).join('')||'<div class="empty-state">Menu vide. Ajoutez des articles dans Réglages.</div>';$$('[data-product]').forEach(b=>b.onclick=()=>addProduct(b.dataset.product));const items=itemsFor(activeOrder.id);$('#ticketTitle').textContent='Commande';$('#ticketMeta').textContent=`${items.length} article${items.length!==1?'s':''}`;$('#ticketList').innerHTML=items.map(i=>`<div class="ticket-row"><div><strong>${esc(i.name)}</strong><span class="item-state ${i.kitchen_status}">${i.kitchen_status==='sent'?'Envoyé':'Nouveau'}</span></div><span>${money(lineAmount(i))}</span><button class="icon-btn" data-remove="${i.id}">×</button></div>`).join('')||'<div class="empty-state small-empty">Touchez un article pour commencer.</div>';$$('[data-remove]').forEach(b=>b.onclick=()=>removeItem(b.dataset.remove));const sub=orderSubtotal(activeOrder.id),tx=calcTax(sub);$('#ticketTotals').innerHTML=totalsHtml(sub,tx.gst,tx.qst,tx.total)}
async function addProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const wasPrinted=Number(activeOrder?.addition_print_count||0)>0;const d=(await rest('order_items',{method:'POST',body:{order_id:activeOrder.id,product_id:p.id,name:p.name,unit_price:p.price,quantity:1,paid_quantity:0,kitchen_status:'new'}}))[0];orderItems.push(d);if(wasPrinted)await logFiscalEvent('item_added_after_invoice',{order_id:activeOrder.id,order_item_id:d.id,payload:{name:p.name,unit_price:Number(p.price)}});renderOrder()}
async function removeItem(id){const i=orderItems.find(x=>x.id===id);if(!i)return;if(i.kitchen_status==='sent'&&!confirm('Article déjà envoyé. L’annuler?'))return;const wasPrinted=Number(activeOrder?.addition_print_count||0)>0;await rest(`order_items?id=eq.${id}`,{method:'PATCH',body:{kitchen_status:'cancelled'}});i.kitchen_status='cancelled';if(wasPrinted)await logFiscalEvent('item_removed_after_invoice',{order_id:i.order_id,order_item_id:i.id,payload:{name:i.name,unit_price:Number(i.unit_price)}});renderOrder()}
async function updateGuests(){const n=Number(prompt('Nombre de clients',activeOrder.guest_count));if(!Number.isInteger(n)||n<1)return;await rest(`orders?id=eq.${activeOrder.id}`,{method:'PATCH',body:{guest_count:n,updated_at:new Date().toISOString()}});activeOrder.guest_count=n;renderOrder()}
const printer=role=>printers.find(p=>p.role===role&&p.enabled);
async function savePrinter(role,ip){const p=printer(role);if(p){const d=(await rest(`printers?id=eq.${p.id}`,{method:'PATCH',body:{ip_address:ip,port:9100,enabled:!!ip}}))[0];Object.assign(p,d)}else if(ip)printers.push((await rest('printers',{method:'POST',body:{restaurant_id:restaurant.id,name:role==='kitchen'?'Cuisine':'Reçu',role,ip_address:ip,port:9100,enabled:true}}))[0])}
async function printText(text,role){const p=printer(role);if(!p?.ip_address)throw new Error(`IP imprimante ${role==='kitchen'?'cuisine':'reçu'} manquante`);const r=await fetch('/print',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:p.ip_address,port:p.port||9100,text,cut:true})});if(!r.ok)throw new Error('Imprimante inaccessible');return r.json()}
async function sendKitchen(){const items=itemsFor(activeOrder.id).filter(i=>i.kitchen_status==='new');if(!items.length)return toast('Rien de nouveau');const table=tables.find(t=>t.id===activeOrder.table_id);
  // A shared item is one physical dish split into several fractional order_items rows (one
  // per seat, see split_order_item) -- the kitchen must see it once, not once per seat, or it
  // prepares as many portions as there are seats sharing it instead of the one dish ordered.
  const seenGroups=new Set();
  const ticketLines=items.filter(i=>{if(!i.share_group_id)return true;if(seenGroups.has(i.share_group_id))return false;seenGroups.add(i.share_group_id);return true}).map(i=>`1 x ${i.name}`);
  const ticket=`CUISINE\n${table.label||`Table ${table.number}`}\n${ticketLines.join('\n')}\n`;try{await printText(ticket,'kitchen')}catch(e){if(!confirm(`${e.message}. Marquer envoyé quand même?`))return}await Promise.all(items.map(i=>rest(`order_items?id=eq.${i.id}`,{method:'PATCH',body:{kitchen_status:'sent',kitchen_sent_at:new Date().toISOString()}})));items.forEach(i=>i.kitchen_status='sent');renderOrder();toast('Envoyé en cuisine')}
// unit_price alone is only ever the right thing to display when quantity is 1 -- true for
// every item until one gets shared (split_order_item gives each seat a fractional quantity of
// the same unit_price, e.g. a $28.50 tartare split three ways is three rows of unit_price
// 28.50 and quantity ~0.333). Showing raw unit_price for those rows was quietly wrong on the
// ticket, the pay screen and the printed addition alike -- each looked like the full price
// while the subtotal right below correctly summed to the real, shared total.
function lineAmount(i){return Number(i.unit_price)*(Number(i.quantity)-Number(i.paid_quantity||0))}
function selectedItems(){const all=itemsFor(activeOrder.id);return selectedIds.size?all.filter(i=>selectedIds.has(i.id)):all}
function selectedSubtotal(){return round2(selectedItems().reduce((s,i)=>s+lineAmount(i),0))}
function selectedGross(){return calcTax(selectedSubtotal()).total}
function currentDue(){const full=selectedGross();return splitTarget&&splitTarget<full?splitTarget:full}
function renderPay(){if(!activeOrder)return show('tablesScreen');const table=tables.find(t=>t.id===activeOrder.table_id),items=itemsFor(activeOrder.id);$('#payTableLabel').textContent=table.label||`Table ${table.number}`;selectedIds=new Set([...selectedIds].filter(id=>items.some(i=>i.id===id)));$('#payItems').innerHTML=items.map(i=>`<button class="pay-row ${selectedIds.has(i.id)?'selected':''}" data-payitem="${i.id}"><span class="check">${selectedIds.has(i.id)?'✓':''}</span><span>${esc(i.name)}</span><strong>${money(lineAmount(i))}</strong></button>`).join('');$$('[data-payitem]').forEach(b=>b.onclick=()=>{selectedIds.has(b.dataset.payitem)?selectedIds.delete(b.dataset.payitem):selectedIds.add(b.dataset.payitem);splitTarget=null;renderPay()});renderPaySummary()}
function renderPaySummary(){const sub=selectedSubtotal(),tx=calcTax(sub),due=currentDue();$('#selectedSummary').innerHTML=selectedIds.size?`<div class="selection-note">${selectedIds.size} article${selectedIds.size>1?'s':''} sélectionné${selectedIds.size>1?'s':''}</div>`:'<div class="selection-note">Solde complet</div>';$('#payTotals').innerHTML=totalsHtml(sub,tx.gst,tx.qst,tx.total,0,due);$('#baseDue').textContent=money(due);updateTerminalPreview();updateCashPreview()}
function splitAmounts(total,n){const cents=Math.round(total*100),base=Math.floor(cents/n),rem=cents-base*n;return Array.from({length:n},(_,i)=>(base+(i>=n-rem?1:0))/100)}
function renderSplit(n){if(!Number.isInteger(n)||n<2||n>30){splitTarget=null;$('#splitBox').innerHTML='';renderPaySummary();return}const parts=splitAmounts(selectedGross(),n);splitTarget=parts[0];$('#splitBox').innerHTML=`<div class="split-preview">${parts.map((p,i)=>`<div><span>Part ${i+1}</span><strong>${money(p)}</strong></div>`).join('')}</div>`;renderPaySummary()}
function updateTerminalPreview(){const due=currentDue(),v=Number($('#terminalTotal')?.value||0),tip=settings?.tips_enabled&&v>=due?round2(v-due):0;$('#terminalTip').textContent=v?`Pourboire détecté : ${money(tip)}`:'Entrez le total affiché sur le terminal.'}
function updateCashPreview(){const due=currentDue(),received=Number($('#cashReceived')?.value||0),tip=settings?.tips_enabled?Math.max(0,Number($('#cashTip')?.value||0)):0,change=round2(received-due-tip);$('#cashChange').textContent=!received?'Entrez le montant reçu.':change<-0.009?`Montant manquant : ${money(-change)}`:`Monnaie : ${money(Math.max(0,change))}`}
async function submitMev(invoice,liveContext){
  if(settings?.mev_mode==='disabled')return{environment:'DISABLED',status:'disabled',certified:false};
  if(settings?.mev_mode==='live'){
    // Verified against Revenu Québec's real DEV environment (see mev-protocol.js), but only
    // ever exercised from a Node test harness, never from this exact call site on a real
    // device -- submitMevTransaction itself refuses cleanly (status "not_configured") rather
    // than inventing a fiscal outcome when the platform, certificate or partner config isn't
    // ready, so this never has to guess either.
    return submitMevTransaction(liveContext);
  }
  const r=await fetch(CFG.mevSimulatorUrl,{method:'POST',headers:authHeaders(),body:JSON.stringify(invoice)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`MEV simulateur ${r.status}`);return d;
}
function allocationForDue(due){const fullGross=selectedGross(),subAll=selectedSubtotal();if(Math.abs(due-fullGross)<.011)return{sub:subAll,tax:calcTax(subAll),items:selectedItems(),kind:'items'};const ratio=due/fullGross,sub=round2(subAll*ratio),tax=calcTax(sub);tax.total=due;return{sub,tax,items:[],kind:'amount'}}
async function payCard(){const due=currentDue(),terminal=round2(Number($('#terminalTotal').value));if(!terminal||terminal<due-.009)return toast(`Le total terminal doit être au moins ${money(due)}`,'error');const tip=settings?.tips_enabled?round2(terminal-due):0,a=allocationForDue(due);await finalizeInvoice({...a,method:'card',cardType,tipAmount:tip,paymentTotal:terminal,tenderedAmount:terminal,changeDue:0,tipSource:tip?'external_terminal':'none',allocation:splitTarget?{amount:due,split:true}:null})}
async function payCash(){const due=currentDue(),received=round2(Number($('#cashReceived').value)),tip=settings?.tips_enabled?round2(Number($('#cashTip').value||0)):0;if(!received||received<due+tip-.009)return toast(`Montant reçu insuffisant`,'error');const change=round2(received-due-tip),a=allocationForDue(due);await finalizeInvoice({...a,method:'cash',tipAmount:tip,paymentTotal:round2(due+tip),tenderedAmount:received,changeDue:change,tipSource:tip?'manual_cash':'none',allocation:splitTarget?{amount:due,split:true}:null})}
async function payOther(){const due=currentDue(),a=allocationForDue(due);await finalizeInvoice({...a,method:'other',tipAmount:0,paymentTotal:due,tenderedAmount:due,changeDue:0,tipSource:'none',allocation:splitTarget?{amount:due,split:true}:null})}
async function payLeftWithoutPaying(){if(!confirm('Confirmer que la cliente ou le client est parti sans payer? Cette facture sera marquée comme non encaissée.'))return;const due=currentDue(),a=allocationForDue(due);await finalizeInvoice({...a,method:'left_without_paying',tipAmount:0,paymentTotal:due,tenderedAmount:0,changeDue:0,tipSource:'none',allocation:splitTarget?{amount:due,split:true}:null})}
async function finalizeInvoice({items,sub,tax,method,tipAmount,paymentTotal,tenderedAmount,changeDue,tipSource,kind,allocation,cardType}){// The server recomputes subtotal/taxes/total from order_items and the configured
// rates; whatever this client thinks they are is only used for the on-screen preview.
const invRes=await rest('rpc/finalize_invoice',{method:'POST',body:{p_order_id:activeOrder.id,p_item_ids:items.length?items.map(i=>i.id):null,p_amount:items.length?null:round2(tax.total),p_method:method,p_tip_amount:tipAmount,p_tendered_amount:tenderedAmount,p_tip_source:tipSource,p_produced_offline:!navigator.onLine,p_card_type:method==='card'?cardType||null:null}});const inv=Array.isArray(invRes)?invRes[0]:invRes;if(!inv?.id)throw new Error('Facture non créée par le serveur');
// SW-77: Revenu Québec distinguishes "Carte de crédit" (CRE) from "Carte de débit" (DEB) --
// this only changes which MEV modPai code is sent, never payments.method itself (still 'card').
const mevPaymentMethod=method==='card'?`card_${cardType||'credit'}`:method;
let fiscal;try{fiscal=await submitMev(
  {id:inv.id,table_id:activeOrder.table_id,subtotal:Number(inv.subtotal),gst:Number(inv.gst),qst:Number(inv.qst),total:Number(inv.total),tip:Number(inv.tip_amount),payment_total:Number(inv.payment_total),payment_method:mevPaymentMethod,items:items.map(i=>({name:i.name,price:i.unit_price}))},
  {restaurant,invoice:inv,invoiceItems:items.map(i=>({name:i.name,quantity:Number(i.quantity)-Number(i.paid_quantity||0),line_total:round2(Number(i.unit_price)*(Number(i.quantity)-Number(i.paid_quantity||0)))})),paymentMethod:mevPaymentMethod,tableLabel:tables.find(t=>t.id===activeOrder.table_id)?.number,guestCount:activeOrder.guest_count}
);await rest('mev_attempts',{method:'POST',body:{restaurant_id:restaurant.id,invoice_id:inv.id,environment:fiscal.environment||'SIMULATOR',status:fiscal.status,request_payload:{invoice_id:inv.id,total:tax.total},response_payload:fiscal,transaction_id:fiscal.transaction_id,qr_payload:fiscal.qr_payload}})}catch(e){fiscal={environment:'SIMULATOR',status:'network_error',certified:false,error:e.message};await rest('mev_attempts',{method:'POST',body:{restaurant_id:restaurant.id,invoice_id:inv.id,environment:'simulator',status:'network_error',error_code:'NETWORK_ERROR',error_message:e.message,request_payload:{invoice_id:inv.id,total:tax.total}}});await logFiscalEvent('mev_error',{invoice_id:inv.id,error_code:'NETWORK_ERROR',error_message:e.message})}
if(fiscal&&fiscal.status&&fiscal.status!=='accepted'&&fiscal.status!=='network_error')await logFiscalEvent('mev_error',{invoice_id:inv.id,error_code:fiscal.error_code||fiscal.status,error_message:fiscal.error_message||fiscal.error||null,payload:{remote_status:fiscal.remote_status||null}});// finalize_invoice already applied paid_quantity and the order status server-side.
inv.mev_response=fiscal;inv.mev_transaction_id=fiscal.transaction_id;inv.status=mevInvoiceStatus(fiscal.status);invoices.unshift(inv);const closedOrderId=activeOrder.id;await loadAll(true);if(!orders.some(o=>o.id===closedOrderId))activeOrder=null;else activeOrder=orders.find(o=>o.id===closedOrderId);selectedIds.clear();splitTarget=null;showReceipt({...inv,method,items,fiscal,tendered_amount:tenderedAmount,change_due:changeDue})}
function showReceipt(inv){const f=inv.fiscal||inv.mev_response||{},rows=(inv.items||[]).map(i=>`<div class="receipt-line"><span>${esc(i.name)}</span><span>${money(i.unit_price||i.price)}</span></div>`).join('');openModal(`<div class="receipt-modal"><div class="modal-title-row"><div><span class="eyebrow">Facture</span><h2>${inv.method==='left_without_paying'?'Parti sans payer':f.status==='accepted'?'Paiement accepté':'Paiement enregistré'}</h2></div><button class="icon-btn" data-close>×</button></div><div class="receipt-paper"><strong>${esc(restaurant.name)}</strong><div class="receipt-muted">${new Date().toLocaleString('fr-CA')}</div><hr>${rows||'<div class="receipt-muted">Paiement partiel</div>'}<hr>${totalsHtml(inv.subtotal,inv.gst,inv.qst,inv.total,inv.tip_amount,inv.payment_total)}${inv.change_due?`<div class="receipt-line"><span>Monnaie</span><span>${money(inv.change_due)}</span></div>`:''}<div class="receipt-fiscal"><span>MEV</span><strong>${esc(f.transaction_id||f.status||'Non transmis')}</strong><small>${f.certified===false?'SIMULATION — NON CERTIFIÉ':''}</small><code>${esc(f.qr_payload||'')}</code></div></div><div class="button-row"><button id="modalPrint" class="btn primary">Imprimer</button><button class="btn" data-close>Fermer</button></div></div>`);$('#modalPrint').onclick=()=>printReceipt(inv).catch(e=>toast(e.message,'error'))}
// SW-76 4.4: the first addition is "FACTURE ORIGINALE"; once the order changed and it
// is printed again it becomes "FACTURE REVISEE" and must say how many it replaces.
async function printAddition(){
  const table=tables.find(t=>t.id===activeOrder.table_id),sub=orderSubtotal(activeOrder.id),tx=calcTax(sub);
  const printed=Number(activeOrder.addition_print_count||0);
  const heading=printed?['FACTURE RÉVISÉE',`Remplace ${printed} facture${printed>1?'s':''}`]:['FACTURE ORIGINALE'];
  const lines=[companyHeaderLines(),...heading,offlineMarker(),settings?.formation_mode?'MODE FORMATION — TRANSACTION FICTIVE':null,table.label||`Table ${table.number}`,...itemsFor(activeOrder.id).map(i=>`${i.name} ${money(lineAmount(i))}`),`Sous-total ${money(sub)}`,`TPS ${money(tx.gst)}`,`TVQ ${money(tx.qst)}`,`TOTAL ${money(tx.total)}`,''].filter(x=>x!==null&&x!==undefined);
  await printText(lines.join('\n'),'receipt');
  const next=printed+1;
  const updated=(await rest(`orders?id=eq.${activeOrder.id}`,{method:'PATCH',body:{addition_print_count:next,updated_at:new Date().toISOString()}}))[0];
  if(updated)Object.assign(activeOrder,updated);else activeOrder.addition_print_count=next;
  if(printed)await logFiscalEvent('addition_revised',{order_id:activeOrder.id,payload:{replaces:printed}});
  toast(printed?'Facture révisée imprimée':'Addition imprimée');
}
async function printReceipt(inv){const f=inv.fiscal||inv.mev_response||{};const leftFlag=inv.method==='left_without_paying'?'\nPARTI SANS PAYER':'';const offFlag=(inv.produced_offline||offlineMarker())?'\nPROBLÈME DE COMMUNICATION':'';
// SW-73.B says a Formation-mode document must carry a mention, but the exact wording was lost
// to a PDF-conversion artifact in the source guide (see docs/certification-test-cases.md) --
// this is a placeholder pending confirmation, not a transcribed official string.
const formFlag=inv.mode_transaction==='FOR'?'\nMODE FORMATION — TRANSACTION FICTIVE':'';
window.__resto360SetPrintContext?.({invoiceId:inv.id,orderId:inv.order_id||null,certified:f.certified===true,environment:f.environment||null});await printText(`${companyHeaderLines()}\nPAIEMENT REÇU${leftFlag}${offFlag}${formFlag}\nFacture ${inv.id}\nTPS ${money(inv.gst)}\nTVQ ${money(inv.qst)}\nPourboire ${money(inv.tip_amount)}\nTOTAL ${money(inv.payment_total||inv.total)}\n${inv.change_due?`Monnaie ${money(inv.change_due)}\n`:''}MEV ${f.transaction_id||f.status||''}\n${f.qr_payload||''}\n`,'receipt');toast('Reçu envoyé')}
function renderHistory(){$('#historyList').innerHTML=invoices.map(i=>`<div class="history-row"><div><strong>${new Date(i.created_at).toLocaleString('fr-CA')}${i.mode_transaction==='FOR'?' · <span class="muted-inline">FORMATION</span>':''}</strong><span>${i.id.slice(0,8).toUpperCase()} · ${i.mev_transaction_id||'MEV en attente'}</span></div><div><strong>${money(i.payment_total||i.total)}</strong><span class="status-pill ${i.status}">${i.status}</span></div><button class="btn small" data-duplicata="${i.id}">Duplicata</button>${Number(i.subtotal)<0?'':`<button class="btn small" data-credit="${i.id}">Rembourser</button>`}</div>`).join('')||'<div class="empty-state">Aucune facture.</div>';$$('[data-duplicata]').forEach(b=>b.onclick=()=>printDuplicata(b.dataset.duplicata).catch(e=>toast(e.message,'error')));$$('[data-credit]').forEach(b=>b.onclick=()=>createCreditNote(b.dataset.credit).catch(e=>toast(e.message,'error')))}
async function createCreditNote(invoiceId){
  const reason=prompt('Motif du remboursement (note de crédit)');if(reason===null)return;
  // Needed before the RPC call: create_credit_note() only writes the negative invoice header,
  // never invoice_items, and by the time it returns the original invoice_items/payments could
  // in principle have changed under us (they won't in practice, but reading first is free).
  const [srcRows,srcItems,payRows]=await Promise.all([
    rest(`invoices?id=eq.${invoiceId}&select=*&limit=1`),
    rest(`invoice_items?invoice_id=eq.${invoiceId}&select=*`),
    rest(`payments?invoice_id=eq.${invoiceId}&select=method&limit=1`),
  ]);
  const src=srcRows?.[0];if(!src)throw new Error('Facture originale introuvable');
  const res=await rest('rpc/create_credit_note',{method:'POST',body:{p_invoice_id:invoiceId,p_reason:reason||null}});
  const note=Array.isArray(res)?res[0]:res;if(!note?.id)throw new Error('Note de crédit non créée');
  // SW-73 4.4.1.1.8: each item is repeated with an inversely equal price, not replaced by a
  // single "Annulation" line -- quantity stays positive, only the price flips sign.
  const items=(srcItems||[]).map(i=>({name:i.name,quantity:Number(i.quantity),line_total:-Number(i.line_total)}));
  const paymentMethod=payRows?.[0]?.method||'other';
  let fiscal;
  try{fiscal=await submitMev(
    {id:note.id,subtotal:Number(note.subtotal),gst:Number(note.gst),qst:Number(note.qst),total:Number(note.total),tip:0,payment_total:Number(note.payment_total),payment_method:paymentMethod,items:items.map(i=>({name:i.name,price:i.line_total}))},
    {restaurant,invoice:note,invoiceItems:items,paymentMethod,documentType:'credit_note',
     // Table/comptoir service type for the original sale isn't tracked on the invoice itself,
     // so this always reports as "comptoir" (no tableLabel) rather than guessing wrong.
     replacesTransaction:{noTrans:String(src.invoice_number??src.id),datTrans:datTrans(src.created_at),avantTax:Number(src.subtotal)}}
  )}catch(e){fiscal={environment:'SIMULATOR',status:'network_error',certified:false,error:e.message}}
  await rest('mev_attempts',{method:'POST',body:{restaurant_id:restaurant.id,invoice_id:note.id,environment:fiscal.environment||'SIMULATOR',status:fiscal.status,request_payload:{invoice_id:note.id,total:note.total},response_payload:fiscal,transaction_id:fiscal.transaction_id,qr_payload:fiscal.qr_payload}});
  await printCreditNote(note,reason);await loadAll();renderHistory();toast('Note de crédit créée')
}
async function printCreditNote(note,reason){await printText([companyHeaderLines(),'NOTE DE CRÉDIT',offlineMarker(),note.mode_transaction==='FOR'?'MODE FORMATION — TRANSACTION FICTIVE':null,`Note ${note.invoice_number?`#${note.invoice_number}`:note.id.slice(0,8).toUpperCase()}`,`Annule la facture ${note.replaces_invoice_id?note.replaces_invoice_id.slice(0,8).toUpperCase():''}`,reason?`Motif : ${reason}`:null,'Crédité à : ______________________','Date de la remise : ______________','',`Sous-total ${money(note.subtotal)}`,`TPS ${money(note.gst)}`,`TVQ ${money(note.qst)}`,`TOTAL ${money(note.total)}`,''].filter(x=>x!==null&&x!==undefined).join('\n'),'receipt')}
async function voidActiveOrder(){if(!activeOrder)return;const reason=prompt('Motif de l’annulation de la commande');if(reason===null)return;const table=tables.find(t=>t.id===activeOrder.table_id);const cancelled=itemsFor(activeOrder.id).map(i=>`${i.name}  ${money(lineAmount(i))}`);const orderId=activeOrder.id;await rest('rpc/void_order',{method:'POST',body:{p_order_id:orderId,p_reason:reason||null}});try{await printText([companyHeaderLines(),'COMMANDE ANNULÉE',offlineMarker(),table?(table.label||`Table ${table.number}`):'',reason?`Motif : ${reason}`:null,'',...cancelled,'','AUCUN PAIEMENT PERÇU',''].filter(x=>x!==null&&x!==undefined&&x!=='').join('\n'),'receipt')}catch(e){toast(`Annulation enregistrée, impression échouée : ${e.message}`,'error')}activeOrder=null;await loadAll();show('tablesScreen');toast('Commande annulée')}
async function printDuplicata(invoiceId){const invRows=await rest(`invoices?id=eq.${invoiceId}&select=*&limit=1`);const inv=invRows?.[0];if(!inv)throw new Error('Facture introuvable');const items=await rest(`invoice_items?invoice_id=eq.${invoiceId}&select=*`);const lines=(items||[]).map(l=>`${l.quantity} x ${money(l.unit_price)}  ${money(l.line_total)}`);await printText(`${companyHeaderLines()}\n*** COPIE DU COMMERÇANT ***\nNE PAS REMETTRE AU CLIENT\nFacture ${inv.invoice_number?`#${inv.invoice_number}`:inv.id.slice(0,8).toUpperCase()}\n${lines.join('\n')}\nSous-total ${money(inv.subtotal)}\nTPS ${money(inv.gst)}\nTVQ ${money(inv.qst)}\nTOTAL ${money(inv.payment_total||inv.total)}\n`,'receipt');toast('Duplicata imprimé')}
function renderSettings(){$('#menuAdminList').innerHTML=products.map(p=>`<div class="admin-row"><div><strong>${esc(p.name)}</strong><span>${esc(p.category||'AUTRES')} · ${money(p.price)}</span></div><button class="btn small" data-edit-product="${p.id}">Modifier</button></div>`).join('')||'<div class="empty-state">Menu vide.</div>';$$('[data-edit-product]').forEach(b=>b.onclick=()=>productModal(products.find(p=>p.id===b.dataset.editProduct)));$('#tipsEnabled').checked=!!settings?.tips_enabled;$('#kitchenIp').value=printer('kitchen')?.ip_address||'';$('#receiptIp').value=printer('receipt')?.ip_address||'';$('#mevMode').value=settings?.mev_mode||'simulator';updateMevModeWarning();$('#formationMode').checked=!!settings?.formation_mode;updateFormationBanner();$('#companyLegalName').value=restaurant.legal_name||'';$('#companyAddress').value=restaurant.address||'';$('#companyCity').value=restaurant.city||'';$('#companyPostalCode').value=restaurant.postal_code||'';$('#companyPhone').value=restaurant.phone||'';$('#companyGst').value=restaurant.gst_number||'';$('#companyQst').value=restaurant.qst_number||'';const isOwner=user?.id===restaurant.owner_id;$$('#companySettings input').forEach(i=>i.disabled=!isOwner);$('#saveCompanyInfo').disabled=!isOwner;$('#companyOwnerNote').textContent=isOwner?"Renseignements exigés sur les factures et reçus (guide SW-76).":"Seul le ou la propriétaire du compte peut modifier ces informations.";$('#staffSettings').classList.toggle('hidden',!isOwner);if(isOwner)loadStaffIfNeeded();const y=new Date().getFullYear();$('#reportYear').innerHTML=`<option value="${y}">${y}</option><option value="${y-1}">${y-1}</option>`}
async function generateUserReport(){
  const year=Number($('#reportYear').value)||new Date().getFullYear();
  const from=`${year}-01-01T00:00:00.000Z`,to=`${year+1}-01-01T00:00:00.000Z`;
  // mode_transaction=eq.OPE: SW-73 4.4.1.1.16 -- Formation-mode sales are real transmissions
  // but must never be comptabilisées dans les ventes courantes de l'exploitant.
  const rows=await rest(`invoices?restaurant_id=eq.${restaurant.id}&status=eq.accepted&mode_transaction=eq.OPE&created_at=gte.${from}&created_at=lt.${to}&select=subtotal,gst,qst,total,invoice_number,created_at&order=created_at.desc`);
  const list=rows||[];
  const summary=list.reduce((s,i)=>({count:s.count+1,subtotal:round2(s.subtotal+Number(i.subtotal)),gst:round2(s.gst+Number(i.gst)),qst:round2(s.qst+Number(i.qst)),total:round2(s.total+Number(i.total))}),{count:0,subtotal:0,gst:0,qst:0,total:0});
  const last=list[0];
  const saved=(await rest('user_reports',{method:'POST',body:{restaurant_id:restaurant.id,period_year:year,sales_count:summary.count,sales_subtotal:summary.subtotal,sales_gst:summary.gst,sales_qst:summary.qst,sales_total:summary.total,last_invoice_number:last?.invoice_number||null,last_invoice_at:last?.created_at||null}}))[0];
  // SW-77 Cas 103/603 / SW-78 FO-110: the report itself must be transmitted to the MEV-WEB as a
  // "document" request, not just printed -- this used to only ever print locally.
  if(settings?.mev_mode==='live'){
    try{
      const result=await submitMevUserReport({restaurant,report:{...saved,user_name:session?.user?.email},lastInvoice:last||null,loginAt:localStorage.getItem('resto360-login-at')});
      if(result.status==='accepted')toast('Rapport transmis au MEV-WEB');
      else if(result.status==='not_configured')toast(result.error||'Transmission MEV non configurée','error');
      else toast(`Rapport : ${result.error_message||result.status}`,'error');
    }catch(e){toast(`Transmission MEV du rapport échouée : ${e.message}`,'error')}
  }
  showUserReport(saved)
}
function showUserReport(r){openModal(`<div class="receipt-modal"><div class="modal-title-row"><div><span class="eyebrow">Rapport</span><h2>Rapport de l'utilisateur ${r.period_year}</h2></div><button class="icon-btn" data-close>×</button></div><div class="receipt-paper">${esc(companyHeaderLines()).replace(/\n/g,'<br>')}<hr><div class="receipt-line"><span>Nombre de transactions</span><span>${r.sales_count}</span></div><div class="receipt-line"><span>Sous-total</span><span>${money(r.sales_subtotal)}</span></div><div class="receipt-line"><span>TPS</span><span>${money(r.sales_gst)}</span></div><div class="receipt-line"><span>TVQ</span><span>${money(r.sales_qst)}</span></div><div class="receipt-line"><span>Total</span><span>${money(r.sales_total)}</span></div><hr><div class="receipt-muted">Dernière facture : ${r.last_invoice_number?`#${r.last_invoice_number}`:'aucune'}${r.last_invoice_at?` · ${new Date(r.last_invoice_at).toLocaleString('fr-CA')}`:''}</div></div><div class="button-row"><button id="modalPrintReport" class="btn primary">Imprimer</button><button class="btn" data-close>Fermer</button></div></div>`);$('#modalPrintReport').onclick=()=>printUserReport(r).catch(e=>toast(e.message,'error'))}
async function printUserReport(r){await printText(`${companyHeaderLines()}\nRAPPORT DE L'UTILISATEUR ${r.period_year}\nNombre de transactions ${r.sales_count}\nSous-total ${money(r.sales_subtotal)}\nTPS ${money(r.sales_gst)}\nTVQ ${money(r.sales_qst)}\nTOTAL ${money(r.sales_total)}\nDerniere facture ${r.last_invoice_number?`#${r.last_invoice_number}`:'aucune'}\n`,'receipt');toast('Rapport imprimé')}
// Staff access (add_restaurant_member/list_restaurant_members/remove_restaurant_member, see
// 20260822_000036_staff_accounts.sql) -- until now nothing could ever add a second account to a
// restaurant, so multi-user was broken by omission, not by RLS. Owner-only, same as company info.
let staffMembers=[],staffLoadedFor=null;
async function loadStaffIfNeeded(){if(staffLoadedFor===restaurant.id)return;staffLoadedFor=restaurant.id;try{staffMembers=await rest('rpc/list_restaurant_members',{method:'POST',body:{}})}catch(e){staffMembers=[]}renderStaffList()}
function renderStaffList(){const el=$('#staffList');if(!el)return;el.innerHTML=staffMembers.map(m=>`<div class="admin-row"><div><strong>${esc(m.email)}</strong><span>${m.role==='manager'?'Gérant':'Staff'}</span></div><button class="btn small" data-remove-staff="${m.user_id}">Retirer</button></div>`).join('')||'<div class="empty-state">Personne d\'autre n\'a accès pour le moment.</div>';$$('[data-remove-staff]').forEach(b=>b.onclick=()=>removeStaff(b.dataset.removeStaff))}
async function addStaff(){const email=$('#staffEmail').value.trim();if(!email)return toast('Courriel requis','error');const role=$('#staffRole').value;try{await rest('rpc/add_restaurant_member',{method:'POST',body:{p_email:email,p_role:role}});$('#staffEmail').value='';staffLoadedFor=null;await loadStaffIfNeeded();toast('Accès accordé')}catch(e){toast(e.message,'error')}}
async function removeStaff(userId){if(!confirm('Retirer l\'accès de cette personne?'))return;try{await rest('rpc/remove_restaurant_member',{method:'POST',body:{p_user_id:userId}});staffLoadedFor=null;await loadStaffIfNeeded();toast('Accès retiré')}catch(e){toast(e.message,'error')}}
async function saveCompanyInfo(){const body={legal_name:$('#companyLegalName').value.trim()||null,address:$('#companyAddress').value.trim()||null,city:$('#companyCity').value.trim()||null,postal_code:$('#companyPostalCode').value.trim()||null,phone:$('#companyPhone').value.trim()||null,gst_number:$('#companyGst').value.trim()||null,qst_number:$('#companyQst').value.trim()||null};const d=(await rest(`restaurants?id=eq.${restaurant.id}`,{method:'PATCH',body}))[0];Object.assign(restaurant,d);toast('Coordonnées enregistrées')}
function productModal(p=null){openModal(`<form id="productForm"><div class="modal-title-row"><div><span class="eyebrow">Menu</span><h2>${p?'Modifier':'Nouvel'} article</h2></div><button type="button" class="icon-btn" data-close>×</button></div><label>Nom<input id="pName" required value="${esc(p?.name||'')}"></label><div class="form-two"><label>Prix<input id="pPrice" type="number" min="0" step="0.01" required value="${p?.price??''}"></label><label>Catégorie<input id="pCategory" required value="${esc(p?.category||'PLATS')}"></label></div><label>Station<select id="pStation"><option value="kitchen">Cuisine</option><option value="bar">Bar</option><option value="none">Aucune</option></select></label><div class="button-row"><button class="btn primary">Enregistrer</button>${p?'<button type="button" class="btn danger" id="deleteProduct">Désactiver</button>':''}</div></form>`);$('#pStation').value=p?.kitchen_station||'kitchen';$('#productForm').onsubmit=async e=>{e.preventDefault();const nameErr=srmNameError($('#pName').value);if(nameErr)return toast(nameErr,'error');try{const body={restaurant_id:restaurant.id,name:$('#pName').value.trim(),price:Number($('#pPrice').value),category:$('#pCategory').value.trim().toUpperCase(),kitchen_station:$('#pStation').value,updated_at:new Date().toISOString()};if(p)Object.assign(p,(await rest(`products?id=eq.${p.id}`,{method:'PATCH',body}))[0]);else products.push((await rest('products',{method:'POST',body}))[0]);closeModal();renderSettings();toast('Menu enregistré')}catch(err){toast(err.message,'error')}};if(p)$('#deleteProduct').onclick=async()=>{if(!confirm('Désactiver cet article?'))return;try{await rest(`products?id=eq.${p.id}`,{method:'PATCH',body:{active:false}});products=products.filter(x=>x.id!==p.id);closeModal();renderSettings()}catch(err){toast(err.message,'error')}}}
function updateMevModeWarning(){const el=$('#mevModeWarning');if(!el)return;const mode=$('#mevMode').value;el.textContent=mode==='live'?'Chaque paiement sera transmis pour vrai à Revenu Québec (ou refusé proprement si l’enrôlement n’est pas complet). Vérifiez l’environnement dans Enrôlement MEV-WEB avant d’activer.':mode==='disabled'?'Aucune transmission, aucun document fiscal produit.':'Le simulateur conserve le même flux facture → transmission → journal.'}
async function saveSettings(){try{const d=(await rest(`app_settings?restaurant_id=eq.${restaurant.id}`,{method:'PATCH',body:{tips_enabled:$('#tipsEnabled').checked,mev_mode:$('#mevMode').value,formation_mode:$('#formationMode').checked,updated_at:new Date().toISOString()}}))[0];settings={...settings,...d};updateMevModeWarning();updateFormationBanner();toast('Réglages enregistrés')}catch(err){$('#tipsEnabled').checked=!!settings?.tips_enabled;$('#mevMode').value=settings?.mev_mode||'simulator';$('#formationMode').checked=!!settings?.formation_mode;updateMevModeWarning();updateFormationBanner();toast(err.message,'error')}}
// SW-73.B: "le SEV doit indiquer clairement à l'écran" that Formation mode is active -- a
// persistent banner, same idea as demo-mode.js's, but this one is a real transmission mode.
function updateFormationBanner(){const active=!!settings?.formation_mode;let el=$('#formationBanner');if(active){if(!el){el=document.createElement('div');el.id='formationBanner';el.style.cssText='position:fixed;top:0;left:0;right:0;z-index:9998;background:#a15c00;color:#fff;text-align:center;font-weight:750;font-size:12px;padding:6px;letter-spacing:.03em';el.textContent='MODE FORMATION — TRANSACTIONS FICTIVES, NON COMPTABILISÉES';document.body.appendChild(el)}}else if(el){el.remove()}}
async function addTable(){const n=Number(prompt('Numéro de table'));if(!Number.isInteger(n)||n<1)return;try{tables.push((await rest('restaurant_tables',{method:'POST',body:{restaurant_id:restaurant.id,number:n,sort_order:tables.length}}))[0]);renderTables()}catch(e){toast(e.message,'error')}}
function openModal(html){$('#modalCard').innerHTML=html;$('#modal').classList.add('show');$$('[data-close]').forEach(b=>b.onclick=closeModal)}function closeModal(){$('#modal').classList.remove('show');$('#modalCard').innerHTML=''}
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';try{await login($('#authEmail').value.trim(),$('#authPassword').value)}catch(err){$('#authError').textContent=err.message}};$('#signupBtn').onclick=async()=>{try{await signup($('#authEmail').value.trim(),$('#authPassword').value)}catch(err){$('#authError').textContent=err.message}};$('#logoutBtn').onclick=logout;$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));$('#newTableBtn').onclick=addTable;$('#guestButton').onclick=updateGuests;$('#sendKitchen').onclick=sendKitchen;$('#voidOrder').onclick=()=>voidActiveOrder().catch(e=>toast(e.message,'error'));$('#printAddition').onclick=()=>printAddition().catch(e=>toast(e.message,'error'));$('#goPay').onclick=()=>{selectedIds.clear();splitTarget=null;show('payScreen')};$$('[data-split]').forEach(b=>b.onclick=()=>renderSplit(Number(b.dataset.split)));$$('#cardTypeToggle [data-card-type]').forEach(b=>b.onclick=()=>{cardType=b.dataset.cardType;$$('#cardTypeToggle [data-card-type]').forEach(x=>x.classList.toggle('active',x===b))});$('#customSplit').oninput=e=>renderSplit(Number(e.target.value));$('#terminalTotal').oninput=updateTerminalPreview;$('#cashReceived').oninput=updateCashPreview;$('#cashTip').oninput=updateCashPreview;$('#payCardBtn').onclick=()=>payCard().catch(e=>toast(e.message,'error'));$('#payCashBtn').onclick=()=>payCash().catch(e=>toast(e.message,'error'));$('#payOtherBtn').onclick=()=>payOther().catch(e=>toast(e.message,'error'));$('#payLeftBtn').onclick=()=>payLeftWithoutPaying().catch(e=>toast(e.message,'error'));$('#newProductBtn').onclick=()=>productModal();$('#tipsEnabled').onchange=saveSettings;$('#mevMode').onchange=saveSettings;$('#formationMode').onchange=saveSettings;$('#saveCompanyInfo').onclick=()=>saveCompanyInfo().catch(e=>toast(e.message,'error'));$('#addStaffBtn').onclick=()=>addStaff();$('#generateReportBtn').onclick=()=>generateUserReport().catch(e=>toast(e.message,'error'));$('#savePrinters').onclick=async()=>{try{await savePrinter('kitchen',$('#kitchenIp').value.trim());await savePrinter('receipt',$('#receiptIp').value.trim());toast('Imprimantes enregistrées')}catch(e){toast(e.message,'error')}};$('#testKitchen').onclick=()=>printText('TEST CUISINE\nResto360\n','kitchen').then(()=>toast('Test envoyé')).catch(e=>toast(e.message,'error'));$('#testReceipt').onclick=()=>printText('TEST RECU\nResto360\n','receipt').then(()=>toast('Test envoyé')).catch(e=>toast(e.message,'error'));$('#refreshHistory').onclick=()=>loadAll().then(renderHistory);$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};// SW-76 4.6: offline-mode activation and deactivation must be journalised.
window.addEventListener('offline',()=>{if(restaurant)logFiscalEvent('offline_mode_on')});
window.addEventListener('online',()=>{if(restaurant){logFiscalEvent('offline_mode_off');flushMevQueue(restaurant).then(r=>{if(r.sent)toast(`${r.sent} vente${r.sent>1?'s':''} MEV en attente transmise${r.sent>1?'s':''}`)}).catch(e=>toast(`File MEV: ${e.message}`,'error'))}});
// Also try on boot in case the app was closed while transactions were still queued offline.
setTimeout(()=>{if(restaurant&&navigator.onLine)flushMevQueue(restaurant).catch(()=>{})},4000);
// payment-hook.js prints the pre-payment addition too; let it reuse this one so the
// FACTURE ORIGINALE / REVISEE counter stays in one place.
window.Resto360PrintAddition=()=>printAddition();
// pivots.js splits a shared item server-side; reload so the ticket reflects it.
window.addEventListener('resto360-reload',()=>{if(restaurant)loadAll(true).then(renderCurrent).catch(()=>{})});
setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'}),1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(session?.access_token)boot();