const TAX = { gst: 0.05, qst: 0.09975 };
const products = [
  {id:'burger',name:'Burger classique',price:18.50,cat:'PLATS',cls:'c1'},
  {id:'poutine',name:'Poutine',price:14.00,cat:'PLATS',cls:'c2'},
  {id:'tartare',name:'Tartare saumon',price:22.00,cat:'PLATS',cls:'c3'},
  {id:'beer',name:'Bière blonde',price:8.00,cat:'BOISSONS',cls:'c4'},
  {id:'coke',name:'Coke',price:4.25,cat:'BOISSONS',cls:'c5'},
  {id:'cake',name:'Cheesecake',price:9.50,cat:'DESSERTS',cls:'c6'},
  {id:'salad',name:'Salade César',price:16.00,cat:'ENTRÉES',cls:'c1'},
  {id:'fries',name:'Frites',price:6.00,cat:'ENTRÉES',cls:'c2'},
  {id:'coffee',name:'Café',price:3.75,cat:'BOISSONS',cls:'c5'}
];
const defaultState = () => ({
  activeTableId:null,
  tables:[12,13,14,15,20,21,22,31].map(id=>({id,guests:0,openedAt:null,status:'free',items:[]})),
  invoices:[],
  settings:{kitchenIp:window.SIMPLEPOS_CONFIG?.kitchenPrinterIp||'',receiptIp:window.SIMPLEPOS_CONFIG?.receiptPrinterIp||'',mevMode:'mock'}
});
let state = load(); let selectedIds = new Set(); let activeCategory = 'TOUS'; let lastReceipt=null;
function load(){try{return JSON.parse(localStorage.getItem('simplepos-state'))||defaultState()}catch{return defaultState()}}
function save(){localStorage.setItem('simplepos-state',JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function money(n){return Number(n).toLocaleString('fr-CA',{style:'currency',currency:'CAD'})}
function round2(n){return Math.round((n+Number.EPSILON)*100)/100}
function calcTax(sub){const gst=round2(sub*TAX.gst),qst=round2(sub*TAX.qst);return {gst,qst,total:round2(sub+gst+qst)}}
function uid(prefix='id'){return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
function activeTable(){return state.tables.find(t=>t.id===state.activeTableId)}
function unpaidItems(t){return t.items.filter(i=>!i.paid)}
function subtotal(t){return round2(unpaidItems(t).reduce((s,i)=>s+i.price,0))}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='tablesScreen')renderTables();if(id==='orderScreen')renderOrder();if(id==='payScreen')renderPay();if(id==='historyScreen')renderHistory();if(id==='settingsScreen')renderSettings()}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function openTable(id){let t=state.tables.find(x=>x.id===id);if(t.status==='free'){t.status='open';t.guests=1;t.openedAt=Date.now()}state.activeTableId=id;save();show('orderScreen')}
function renderTables(){const grid=$('#tablesGrid');grid.innerHTML=state.tables.map(t=>{const sub=subtotal(t),tax=calcTax(sub);const open=t.status!=='free';return `<div class="table ${open?'open':'free'}" data-table="${t.id}"><h3>Table ${t.id}</h3><div class="small">${open?`${t.guests} client${t.guests>1?'s':''}<br>${unpaidItems(t).length} article${unpaidItems(t).length>1?'s':''}<br><strong style="color:#fff">${money(tax.total)}</strong>`:'Libre'}</div></div>`}).join('');$$('[data-table]').forEach(el=>el.onclick=()=>openTable(Number(el.dataset.table)))}
function renderCategories(){const cats=['TOUS','ENTRÉES','PLATS','BOISSONS','DESSERTS'];$('#categories').innerHTML=cats.map(c=>`<div class="cat ${c===activeCategory?'active':''}" data-cat="${c}">${c}</div>`).join('');$$('[data-cat]').forEach(el=>el.onclick=()=>{activeCategory=el.dataset.cat;renderOrder()})}
function renderOrder(){const t=activeTable();if(!t)return show('tablesScreen');renderCategories();$('#orderTableLabel').textContent=`Table ${t.id}`;$('#guestButton').textContent=`${t.guests} client${t.guests>1?'s':''}`;$('#guestButton').onclick=()=>{const n=Number(prompt('Nombre de clients',t.guests));if(Number.isInteger(n)&&n>0){t.guests=n;save();renderOrder()}};$('#ticketTitle').textContent=`Table ${t.id}`;$('#ticketMeta').textContent=`${unpaidItems(t).length} article(s) • ${t.guests} client(s)`;
  const filtered=activeCategory==='TOUS'?products:products.filter(p=>p.cat===activeCategory);$('#products').innerHTML=filtered.map(p=>`<div class="product ${p.cls}" data-product="${p.id}"><span>${p.name}</span><small>${money(p.price)}</small></div>`).join('');$$('[data-product]').forEach(el=>el.onclick=()=>addProduct(el.dataset.product));
  const items=unpaidItems(t);$('#ticketList').innerHTML=items.length?items.map(i=>`<div class="row"><div class="qty">1</div><div>${i.name}<br><span class="${i.kitchenStatus==='sent'?'sent':'new'}">${i.kitchenStatus==='sent'?'ENVOYÉ':'NOUVEAU'}</span></div><strong>${money(i.price)}</strong><button class="btn red" data-remove="${i.id}" style="padding:5px">×</button></div>`).join(''):'<div class="row"><div></div><div class="small">Aucun article</div><div></div><div></div></div>';$$('[data-remove]').forEach(el=>el.onclick=()=>removeItem(el.dataset.remove));const sub=subtotal(t),tax=calcTax(sub);$('#ticketTotals').innerHTML=`<div class="tr"><span>Sous-total</span><span>${money(sub)}</span></div><div class="tr"><span>TPS</span><span>${money(tax.gst)}</span></div><div class="tr"><span>TVQ</span><span>${money(tax.qst)}</span></div><div class="tr grand"><span>Total</span><span>${money(tax.total)}</span></div>`}
function addProduct(id){const t=activeTable(),p=products.find(x=>x.id===id);t.items.push({id:uid('item'),productId:p.id,name:p.name,price:p.price,kitchenStatus:'new',paid:false});save();renderOrder()}
function removeItem(id){const t=activeTable(),i=t.items.findIndex(x=>x.id===id);if(i<0)return;if(t.items[i].kitchenStatus==='sent'&&!confirm('Cet article a déjà été envoyé en cuisine. Le retirer quand même?'))return;t.items.splice(i,1);save();renderOrder()}
async function sendKitchen(){const t=activeTable(),items=unpaidItems(t).filter(i=>i.kitchenStatus==='new');if(!items.length)return toast('Aucun nouvel article');const ticket=`CUISINE\nTable ${t.id}\n${items.map(i=>`1 x ${i.name}`).join('\n')}\n`;try{await printText(ticket,'kitchen');items.forEach(i=>i.kitchenStatus='sent');save();renderOrder();toast('Commande envoyée en cuisine')}catch(e){toast('Impression échouée : '+e.message)}}
function renderPay(){const t=activeTable();if(!t)return show('tablesScreen');$('#payTableLabel').textContent=`Table ${t.id}`;const items=unpaidItems(t);selectedIds=new Set([...selectedIds].filter(id=>items.some(i=>i.id===id)));$('#payItems').innerHTML=items.map(i=>`<div class="pay-item ${selectedIds.has(i.id)?'selected':''}" data-payitem="${i.id}"><div class="checkbox">${selectedIds.has(i.id)?'✓':''}</div><div>${i.name}</div><strong>${money(i.price)}</strong></div>`).join('');$$('[data-payitem]').forEach(el=>el.onclick=()=>{const id=el.dataset.payitem;selectedIds.has(id)?selectedIds.delete(id):selectedIds.add(id);renderPay()});renderPaySummary()}
function selectedItems(){const t=activeTable();return unpaidItems(t).filter(i=>selectedIds.has(i.id))}
function renderPaySummary(){const t=activeTable(),sel=selectedItems(),base=sel.length?round2(sel.reduce((s,i)=>s+i.price,0)):subtotal(t),tax=calcTax(base);$('#selectedSummary').innerHTML=sel.length?sel.map(i=>`<div class="tr"><span>${i.name}</span><span>${money(i.price)}</span></div>`).join(''):'<div class="small">Aucun article sélectionné : le paiement couvrira le solde complet.</div>';$('#payTotals').innerHTML=`<div class="tr"><span>Sous-total</span><span>${money(base)}</span></div><div class="tr"><span>TPS</span><span>${money(tax.gst)}</span></div><div class="tr"><span>TVQ</span><span>${money(tax.qst)}</span></div><div class="tr grand"><span>À payer</span><span>${money(tax.total)}</span></div>`}
function splitAmounts(total,n){const cents=Math.round(total*100),base=Math.floor(cents/n),rem=cents-base*n;return Array.from({length:n},(_,i)=>(base+(i>=n-rem?1:0))/100)}
function renderSplit(n){const t=activeTable(),total=calcTax(subtotal(t)).total;if(!Number.isInteger(n)||n<2||n>30)return;const parts=splitAmounts(total,n);$('#splitBox').innerHTML=`<div class="summary"><strong>${n} parts</strong>${parts.map((p,i)=>`<div class="tr"><span>Part ${i+1}</span><span>${money(p)}</span></div>`).join('')}<button class="btn green" id="payFirstPart">Payer la prochaine part (${money(parts[0])})</button></div>`;$('#payFirstPart').onclick=()=>payByAmount(parts[0],'Carte')}
async function mevSubmit(invoice){if(state.settings.mevMode==='disabled')return {status:'disabled',transactionId:null};try{const r=await fetch('/api/mev/mock',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(invoice)});if(!r.ok)throw new Error('MEV mock indisponible');return await r.json()}catch{return {status:'mock-local',transactionId:'MOCK-'+Date.now()}}}
async function pay(method){const t=activeTable(),sel=selectedItems(),items=sel.length?sel:unpaidItems(t);if(!items.length)return toast('Rien à payer');const sub=round2(items.reduce((s,i)=>s+i.price,0)),tax=calcTax(sub);await finalizeInvoice({t,items,sub,tax,method})}
async function payByAmount(amount,method){const t=activeTable();const remaining=calcTax(subtotal(t)).total;if(amount<=0||amount>remaining+0.01)return;const ratio=remaining?amount/remaining:1;const sub=round2(subtotal(t)*ratio);const gst=round2(sub*TAX.gst),qst=round2(sub*TAX.qst);const invoice={id:uid('inv'),tableId:t.id,createdAt:Date.now(),method,kind:'amount',items:[],subtotal:sub,gst,qst,total:round2(sub+gst+qst),allocatedAmount:amount};invoice.total=amount;invoice.mev=await mevSubmit(invoice);state.invoices.unshift(invoice);applyAmountToTable(t,amount);save();showReceipt(invoice);if(subtotal(t)===0)closeTableIfSettled(t)}
function applyAmountToTable(t,amount){let grossLeft=Math.round(amount*100);for(const item of unpaidItems(t)){const gross=Math.round(calcTax(item.price).total*100);if(grossLeft>=gross){item.paid=true;grossLeft-=gross}else if(grossLeft>0){item.price=round2(item.price*(1-grossLeft/gross));grossLeft=0;break}}}
async function finalizeInvoice({t,items,sub,tax,method}){const invoice={id:uid('inv'),tableId:t.id,createdAt:Date.now(),method,kind:'items',items:items.map(i=>({id:i.id,name:i.name,price:i.price})),subtotal:sub,gst:tax.gst,qst:tax.qst,total:tax.total};invoice.mev=await mevSubmit(invoice);items.forEach(i=>i.paid=true);state.invoices.unshift(invoice);selectedIds.clear();save();showReceipt(invoice);closeTableIfSettled(t)}
function closeTableIfSettled(t){if(unpaidItems(t).length===0||subtotal(t)<=0){t.status='free';t.guests=0;t.openedAt=null;t.items=[];save()}}
function receiptHtml(inv){return `<div class="receipt"><strong>RESTAURANT DÉMO</strong><br>Table ${inv.tableId}<br><small>${new Date(inv.createdAt).toLocaleString('fr-CA')}</small><hr>${inv.items.length?inv.items.map(i=>`<div style="display:flex;justify-content:space-between"><span>${i.name}</span><span>${money(i.price)}</span></div>`).join(''):'<div>Paiement partiel</div>'}<hr><div style="display:flex;justify-content:space-between"><span>TPS</span><span>${money(inv.gst)}</span></div><div style="display:flex;justify-content:space-between"><span>TVQ</span><span>${money(inv.qst)}</span></div><div style="display:flex;justify-content:space-between"><strong>TOTAL</strong><strong>${money(inv.total)}</strong></div><div style="margin-top:8px">Paiement : ${inv.method}</div><div style="margin-top:8px;font-size:10px">MEV DEV : ${inv.mev?.transactionId||inv.mev?.status||'désactivé'}</div></div>`}
function showReceipt(inv){lastReceipt=inv;$('#receiptPreview').innerHTML=receiptHtml(inv);$('#paymentModal').classList.add('show')}
async function printReceipt(inv=lastReceipt){if(!inv)return;const text=`RESTAURANT DEMO\nTable ${inv.tableId}\n${inv.items.map(i=>`${i.name} ${money(i.price)}`).join('\n')}\nTPS ${money(inv.gst)}\nTVQ ${money(inv.qst)}\nTOTAL ${money(inv.total)}\nPaiement ${inv.method}\nMEV ${inv.mev?.transactionId||inv.mev?.status||''}\n`;await printText(text,'receipt',receiptHtml(inv))}
async function printText(text,role,html){const ip=role==='kitchen'?state.settings.kitchenIp:state.settings.receiptIp;if(!ip)throw new Error(`IP ${role} manquante`);const r=await fetch('/print',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ip,port:9100,text,cut:true})});if(!r.ok){const msg=await r.text();throw new Error(msg||'Impression impossible')}return r.json()}
function renderHistory(){const el=$('#historyList');el.innerHTML=state.invoices.length?state.invoices.map(i=>`<div class="history-entry"><strong>${i.id}</strong> • Table ${i.tableId}<br><span class="small">${new Date(i.createdAt).toLocaleString('fr-CA')} • ${i.method} • ${money(i.total)} • ${i.mev?.transactionId||i.mev?.status||'MEV n/a'}</span></div>`).join(''):'<div class="small">Aucune facture.</div>'}
function renderSettings(){for(const k of ['kitchenIp','receiptIp','mevMode'])$('#'+k).value=state.settings[k]||''}
function saveSettings(){for(const k of ['kitchenIp','receiptIp','mevMode'])state.settings[k]=$('#'+k).value.trim();save();toast('Réglages enregistrés')}
function demoReset(){state=defaultState();const t=state.tables.find(x=>x.id===12);t.status='open';t.guests=3;t.openedAt=Date.now()-38*60000;['burger','burger','poutine','beer','beer','coke','cake','coffee','fries'].forEach((pid,idx)=>{const p=products.find(x=>x.id===pid);t.items.push({id:uid('item'),productId:p.id,name:p.name,price:p.price,kitchenStatus:idx<6?'sent':'new',paid:false})});state.activeTableId=12;save();renderTables();toast('Démo réinitialisée')}
$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));$('#sendKitchen').onclick=sendKitchen;$('#printAddition').onclick=()=>{const t=activeTable();const tax=calcTax(subtotal(t));printText(`ADDITION\nTable ${t.id}\n${unpaidItems(t).map(i=>`${i.name} ${money(i.price)}`).join('\n')}\nTOTAL ${money(tax.total)}\n`,'receipt')};$('#goPay').onclick=()=>{selectedIds.clear();show('payScreen')};$$('[data-method]').forEach(el=>el.onclick=()=>pay(el.dataset.method));$$('[data-split]').forEach(el=>el.onclick=()=>renderSplit(Number(el.dataset.split)));$('#customSplit').oninput=e=>renderSplit(Number(e.target.value));$('#saveSettings').onclick=saveSettings;$('#testKitchen').onclick=()=>printText('TEST CUISINE\nSimplePOS\n','kitchen').then(()=>toast('Test envoyé')).catch(e=>toast(e.message));$('#testReceipt').onclick=()=>printText('TEST RECU\nSimplePOS\n','receipt').then(()=>toast('Test envoyé')).catch(e=>toast(e.message));$('#printReceipt').onclick=()=>printReceipt().catch(e=>toast(e.message));$('#closeReceipt').onclick=()=>{$('#paymentModal').classList.remove('show');show(activeTable()?.status==='free'?'tablesScreen':'orderScreen')};$('#resetDemo').onclick=demoReset;
setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'}),1000);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(!state.tables.some(t=>t.status!=='free'))demoReset();else renderTables();
export {calcTax,splitAmounts};
