const CFG=window.SIMPLEPOS_CONFIG||{};
const API=`${CFG.supabaseUrl}/rest/v1`;
const money=n=>Number(n||0).toLocaleString('fr-CA',{style:'currency',currency:'CAD'});
function auth(){try{const s=JSON.parse(localStorage.getItem('simplepos-session')||'null');return{apikey:CFG.supabasePublishableKey||'',Authorization:`Bearer ${s?.access_token||''}`}}catch{return{}}}
async function get(path){const r=await fetch(`${API}/${path}`,{headers:auth()});if(!r.ok)throw new Error(`Supabase ${r.status}`);return r.json()}
function monthEq(c){const a=Number(c.amount||0);if(c.recurrence==='weekly')return a*52/12;if(c.recurrence==='monthly')return a;if(c.recurrence==='quarterly')return a/3;if(c.recurrence==='yearly')return a/12;if(c.recurrence==='one_time'&&Number(c.amortization_months)>0)return a/Number(c.amortization_months);return 0}
function split(c){const m=monthEq(c);if(c.cost_behavior==='variable')return[0,m];if(c.cost_behavior==='mixed'){const p=Number(c.variable_percent??0.5);return[m*(1-p),m*p]}return[m,0]}
async function calc(){const r=(await get('restaurants?select=id&order=created_at.asc&limit=1'))[0];if(!r)return null;const since=new Date(Date.now()-30*86400000).toISOString();const [costs,invoices]=await Promise.all([get(`business_costs?restaurant_id=eq.${r.id}&active=eq.true&select=amount,recurrence,amortization_months,cost_behavior,variable_percent`),get(`invoices?restaurant_id=eq.${r.id}&created_at=gte.${encodeURIComponent(since)}&status=neq.cancelled&select=total`)]);let fixed=0,variable=0;for(const c of costs){const [f,v]=split(c);fixed+=f;variable+=v}const sales=invoices.reduce((s,i)=>s+Number(i.total||0),0);const vr=sales>0?Math.min(.95,variable/sales):null;const threshold=vr===null?null:fixed/(1-vr);return{fixed,variable,sales,vr,threshold,daily:threshold?threshold/30.44:null}}
async function render(){const host=document.querySelector('#costSummary')||document.querySelector('#dashMetrics');if(!host)return;document.querySelector('#breakEvenPanel')?.remove();const x=await calc().catch(()=>null);if(!x)return;host.insertAdjacentHTML('afterend',`<section id="breakEvenPanel" class="biz-panel" style="margin:16px 0"><div class="screen-head compact"><div><h2>Seuil de rentabilité</h2><p class="muted">Tous les coûts sont inclus : loyer, fonds de commerce amorti, salaires, assurances, logiciels, équipement, inventaire et autres charges.</p></div></div><div class="business-grid" style="padding:0 16px 16px"><div class="metric"><span>Coûts fixes mensuels</span><strong>${money(x.fixed)}</strong></div><div class="metric"><span>Coûts variables mensuels</span><strong>${money(x.variable)}</strong></div><div class="metric"><span>Part variable / ventes</span><strong>${x.vr===null?'—':(x.vr*100).toFixed(1)+' %'}</strong></div><div class="metric"><span>Seuil mensuel</span><strong>${x.threshold===null?'À calculer':money(x.threshold)}</strong></div><div class="metric"><span>Seuil moyen / jour</span><strong>${x.daily===null?'—':money(x.daily)}</strong></div><div class="metric"><span>Ventes 30 jours</span><strong>${money(x.sales)}</strong></div></div></section>`)}
window.addEventListener('click',e=>{const n=e.target.closest?.('[data-nav]')?.dataset?.nav;if(n==='costsScreen'||n==='dashboardScreen')setTimeout(render,200)});
