const CFG=window.RESTO360_CONFIG||{};
const API=`${CFG.supabaseUrl}/rest/v1`;
const money=n=>Number(n||0).toLocaleString('fr-CA',{style:'currency',currency:'CAD'});
function auth(){try{const s=JSON.parse(localStorage.getItem('resto360-session')||'null');return{apikey:CFG.supabasePublishableKey||'',Authorization:`Bearer ${s?.access_token||''}`}}catch{return{}}}
async function get(path){const r=await fetch(`${API}/${path}`,{headers:auth()});if(!r.ok)throw new Error(`Supabase ${r.status}`);return r.json()}
function fixedMonthEq(c){const a=Number(c.amount||0);if(c.frequency==='weekly')return a*52/12;if(c.frequency==='monthly')return a;if(c.frequency==='quarterly')return a/3;if(c.frequency==='yearly')return a/12;if(c.frequency==='one_time'&&Number(c.amortization_months)>0)return a/Number(c.amortization_months);return 0}
async function calc(){const r=(await get('restaurants?select=id&order=created_at.asc&limit=1'))[0];if(!r)return null;const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1).toISOString(),since30=new Date(Date.now()-30*86400000).toISOString();const [fixed,operating,invoices]=await Promise.all([get(`fixed_expenses?restaurant_id=eq.${r.id}&active=eq.true&select=amount,frequency,amortization_months`),get(`business_costs?restaurant_id=eq.${r.id}&active=eq.true&incurred_on=gte.${monthStart.slice(0,10)}&select=amount`),get(`invoices?restaurant_id=eq.${r.id}&created_at=gte.${encodeURIComponent(since30)}&status=neq.cancelled&select=total`)]);const fixedMonthly=fixed.reduce((s,x)=>s+fixedMonthEq(x),0);const operatingMonth=operating.reduce((s,x)=>s+Number(x.amount||0),0);const sales30=invoices.reduce((s,i)=>s+Number(i.total||0),0);const target=fixedMonthly+operatingMonth;const daily=target/30.44;const gap=sales30-target;return{fixedMonthly,operatingMonth,target,daily,sales30,gap}}
async function render(){const host=document.querySelector('#costSummary')||document.querySelector('#dashMetrics');if(!host)return;document.querySelector('#breakEvenPanel')?.remove();const x=await calc().catch(()=>null);if(!x)return;host.insertAdjacentHTML('afterend',`<section id="breakEvenPanel" class="biz-panel" style="margin:16px 0"><div class="screen-head compact"><div><h2>Seuil de rentabilité</h2><p class="muted">Calculé avec les montants réels saisis. Aucun pourcentage à entrer.</p></div></div><div class="business-grid" style="padding:0 16px 16px"><div class="metric"><span>Frais fixes / mois</span><strong>${money(x.fixedMonthly)}</strong></div><div class="metric"><span>Dépenses réelles ce mois</span><strong>${money(x.operatingMonth)}</strong></div><div class="metric"><span>CA minimum à couvrir</span><strong>${money(x.target)}</strong></div><div class="metric"><span>Minimum moyen / jour</span><strong>${money(x.daily)}</strong></div><div class="metric"><span>Ventes 30 jours</span><strong>${money(x.sales30)}</strong></div><div class="metric"><span>${x.gap>=0?'Au-dessus du seuil':'Manque à couvrir'}</span><strong>${money(Math.abs(x.gap))}</strong></div></div></section>`)}
window.addEventListener('click',e=>{const n=e.target.closest?.('[data-nav]')?.dataset?.nav;if(n==='costsScreen'||n==='dashboardScreen')setTimeout(render,350)});
