const CFG=window.RESTO360_CONFIG||{};
const API=`${CFG.supabaseUrl}/rest/v1`;
const FN=`${CFG.supabaseUrl}/functions/v1`;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const money=n=>Number(n||0).toLocaleString('fr-CA',{style:'currency',currency:'CAD'});
const uid=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ctx={restaurant:null,reservations:[],customers:[],tables:[],costs:[],fixed:[],invoices:[],invoiceItems:[],orderItems:[]};
let dashboardPeriod='month';

function session(){return JSON.parse(localStorage.getItem('resto360-session')||'null')}
function headers(extra={}){const s=session();return{apikey:CFG.supabasePublishableKey,Authorization:`Bearer ${s?.access_token||''}`,'Content-Type':'application/json',...extra}}
async function rest(path,{method='GET',body,prefer='return=representation'}={}){const r=await fetch(`${API}/${path}`,{method,headers:headers(prefer?{Prefer:prefer}:{}),body:body===undefined?undefined:JSON.stringify(body)}),t=await r.text(),d=t?JSON.parse(t):null;if(!r.ok)throw new Error(d?.message||`Supabase ${r.status}`);return d}
function toast(m,type='ok'){const e=$('#toast');if(!e)return;e.textContent=m;e.dataset.type=type;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2400)}
function modal(html){$('#modalCard').innerHTML=html;$('#modal').classList.add('show');$('#modalCard').querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#modal').classList.remove('show'))}
function today(){return new Date().toISOString().slice(0,10)}

async function ensureContext(){if(ctx.restaurant)return;ctx.restaurant=(await rest('restaurants?select=*&order=created_at.asc&limit=1'))?.[0]||null;if(!ctx.restaurant)throw new Error('Restaurant introuvable')}
async function loadBusiness(force=false){await ensureContext();if(!force&&ctx._loadedAt&&Date.now()-ctx._loadedAt<2500)return;const rid=ctx.restaurant.id;const req=[
  rest(`reservations?restaurant_id=eq.${rid}&select=*&order=reservation_date.desc,reservation_time.desc&limit=400`),
  rest(`customers?restaurant_id=eq.${rid}&select=*&order=last_seen_at.desc.nullslast,created_at.desc&limit=500`),
  rest(`restaurant_tables?restaurant_id=eq.${rid}&active=eq.true&select=*&order=number.asc`),
  rest(`business_costs?restaurant_id=eq.${rid}&active=eq.true&select=*&order=incurred_on.desc,created_at.desc&limit=800`),
  rest(`invoices?restaurant_id=eq.${rid}&select=*&order=created_at.desc&limit=2000`),
  rest('invoice_items?select=*'),
  rest('order_items?select=*&order=created_at.desc&limit=5000'),
  rest(`fixed_expenses?restaurant_id=eq.${rid}&active=eq.true&select=*`).catch(()=>[])
];
const [r,c,t,b,i,ii,oi,fx]=await Promise.all(req);ctx={...ctx,reservations:r||[],customers:c||[],tables:t||[],costs:b||[],invoices:i||[],invoiceItems:ii||[],orderItems:oi||[],fixed:fx||[],_loadedAt:Date.now()}}

function periodBounds(period){const now=new Date(),end=new Date(now);let start;if(period==='day')start=new Date(now.getFullYear(),now.getMonth(),now.getDate());else if(period==='week'){const d=(now.getDay()+6)%7;start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-d)}else start=new Date(now.getFullYear(),now.getMonth(),1);return{start,end}}
function inRange(value,{start,end}){const d=new Date(value);return d>=start&&d<=end}
function periodLabel(p){return p==='day'?'aujourd’hui':p==='week'?'cette semaine':'ce mois'}
function daysRemaining(period){const now=new Date();if(period==='day')return{value:1,label:'Aujourd’hui'};if(period==='week'){const d=(now.getDay()+6)%7;return{value:7-d,label:`${7-d} jour${7-d>1?'s':''}`}}const end=new Date(now.getFullYear(),now.getMonth()+1,0);const left=Math.max(1,end.getDate()-now.getDate()+1);return{value:left,label:`${left} jour${left>1?'s':''}`}}
function fixedMonthEq(x){const a=Number(x.amount||0);if(x.frequency==='weekly')return a*52/12;if(x.frequency==='monthly')return a;if(x.frequency==='quarterly')return a/3;if(x.frequency==='yearly')return a/12;if(x.frequency==='one_time'&&Number(x.amortization_months)>0)return a/Number(x.amortization_months);return 0}
function fixedForPeriod(period){const monthly=ctx.fixed.reduce((s,x)=>s+fixedMonthEq(x),0);if(period==='day')return monthly/30.44;if(period==='week')return monthly*12/52;return monthly}
function operatingCostsFor(bounds){return ctx.costs.filter(c=>inRange(`${c.incurred_on}T12:00:00`,bounds)).reduce((s,c)=>s+Number(c.amount||0),0)}
function invoicesFor(bounds){return ctx.invoices.filter(i=>i.status!=='cancelled'&&inRange(i.created_at,bounds))}
function customerSpend(id,invoices=ctx.invoices){return invoices.filter(i=>i.customer_id===id&&i.status!=='cancelled').reduce((s,i)=>s+Number(i.payment_total||i.total||0),0)}

function renderServiceSummary(){const cards=$$('#tablesGrid .table-card.occupied');const guests=cards.reduce((s,c)=>{const m=c.querySelector('.table-meta')?.textContent.match(/(\d+) client/);return s+Number(m?.[1]||0)},0);const sales=cards.reduce((s,c)=>{const raw=c.querySelector('.table-total')?.textContent||'';return s+Number(raw.replace(/[^0-9,.-]/g,'').replace(',','.'))},0);if($('#openTablesCount'))$('#openTablesCount').textContent=cards.length;if($('#openGuestsCount'))$('#openGuestsCount').textContent=guests;if($('#openSalesTotal'))$('#openSalesTotal').textContent=money(sales)}

async function renderDashboard(){await loadBusiness(true);const bounds=periodBounds(dashboardPeriod),inv=invoicesFor(bounds),sales=inv.reduce((s,i)=>s+Number(i.total||0),0),transactions=inv.length,knownCustomers=new Set(inv.filter(i=>i.customer_id).map(i=>i.customer_id)).size,avg=transactions?sales/transactions:0;const fixed=fixedForPeriod(dashboardPeriod),operating=operatingCostsFor(bounds),expenses=fixed+operating,result=sales-expenses,pct=expenses>0?Math.min(100,Math.max(0,sales/expenses*100)):100,gap=Math.max(0,expenses-sales),days=daysRemaining(dashboardPeriod);
$('#dashMetrics').innerHTML=`<div class="metric"><span>Ventes ${periodLabel(dashboardPeriod)}</span><strong>${money(sales)}</strong></div><div class="metric"><span>Dépenses à couvrir</span><strong>${money(expenses)}</strong></div><div class="metric ${result>=0?'good':'bad'}"><span>Résultat actuel</span><strong>${result>=0?'+':''}${money(result)}</strong></div>`;
$('#coverageCard').innerHTML=`<div class="coverage-top"><div><div class="coverage-title">Couverture des dépenses</div><div class="coverage-main">${Math.round(pct)} % couvert</div></div><div class="coverage-gap"><span>${gap>0?'Il manque':'Dépenses couvertes'}</span><strong class="${gap>0?'negative-text':'positive-text'}">${gap>0?money(gap):'✓'}</strong></div></div><div class="coverage-progress"><div style="width:${pct}%"></div></div><div class="coverage-foot"><p>${gap>0?`Les ventes couvrent ${Math.round(pct)} % des dépenses connues ${periodLabel(dashboardPeriod)}.`:`Les ventes couvrent les dépenses connues ${periodLabel(dashboardPeriod)}.`}</p><div class="days-chip">${dashboardPeriod==='day'?'Période':'Jours restants'}<strong>${days.label}</strong></div></div>`;
$('#quickStats').innerHTML=`<div class="quick-stat"><span>Ticket moyen</span><strong>${money(avg)}</strong></div><div class="quick-stat"><span>Transactions</span><strong>${transactions}</strong></div><div class="quick-stat"><span>Clients connus</span><strong>${knownCustomers}</strong></div>`;
renderPopularProducts(inv);renderExpenseHighlights(bounds,fixed);const top=ctx.customers.map(c=>({...c,spend:customerSpend(c.id,inv)})).filter(c=>c.spend>0).sort((a,b)=>b.spend-a.spend).slice(0,8);$('#customerStats').innerHTML=top.map(c=>`<div class="biz-row"><div><strong>${esc(c.name)}</strong><span>${esc(c.phone||c.email||'')}</span></div><strong>${money(c.spend)}</strong></div>`).join('')||'<div class="empty-state">Aucune vente reliée à un client pour cette période.</div>'}
function renderPopularProducts(invoices){const invoiceIds=new Set(invoices.map(i=>i.id)),rows=ctx.invoiceItems.filter(x=>invoiceIds.has(x.invoice_id));const byOrderItem=new Map(ctx.orderItems.map(x=>[x.id,x]));const stats=new Map();rows.forEach(x=>{const oi=byOrderItem.get(x.order_item_id),name=oi?.name||'Article';const cur=stats.get(name)||{qty:0,revenue:0};cur.qty+=Number(x.quantity||0);cur.revenue+=Number(x.line_total||Number(x.unit_price||0)*Number(x.quantity||0));stats.set(name,cur)});const top=[...stats.entries()].sort((a,b)=>b[1].qty-a[1].qty).slice(0,5);$('#popularProducts').innerHTML=top.map(([name,v],idx)=>`<div class="biz-row"><div><strong>${idx+1}. ${esc(name)}</strong><span>${v.qty} vendu${v.qty>1?'s':''}</span></div><strong>${money(v.revenue)}</strong></div>`).join('')||'<div class="empty-state">Les produits populaires apparaîtront après les premières factures.</div>'}
function renderExpenseHighlights(bounds,fixed){const grouped=new Map();ctx.costs.filter(c=>inRange(`${c.incurred_on}T12:00:00`,bounds)).forEach(c=>grouped.set(c.category,(grouped.get(c.category)||0)+Number(c.amount||0)));if(fixed>0)grouped.set('Frais fixes',fixed);const rows=[...grouped.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);$('#expenseHighlights').innerHTML=rows.map(([k,v])=>`<div class="biz-row"><div><strong>${esc(String(k).replaceAll('_',' '))}</strong></div><strong>${money(v)}</strong></div>`).join('')||'<div class="empty-state">Aucune dépense enregistrée pour cette période.</div>'}

async function renderReservations(){await loadBusiness(true);const rows=ctx.reservations.filter(r=>r.status!=='cancelled').slice().sort((a,b)=>`${a.reservation_date} ${a.reservation_time}`.localeCompare(`${b.reservation_date} ${b.reservation_time}`));$('#reservationList').innerHTML=rows.map(r=>{const t=ctx.tables.find(x=>x.id===r.assigned_table_id);return`<div class="biz-row"><div><strong>${esc(r.customer_name)} · ${r.party_size} pers.</strong><span>${r.reservation_date} · ${String(r.reservation_time).slice(0,5)}${t?` · Table ${t.number}`:''} · ${esc(r.status)}</span></div><div class="biz-actions">${['confirmed','arrived'].includes(r.status)?`<button class="btn primary small" data-seat="${r.id}">Asseoir</button>`:''}<button class="btn small" data-editres="${r.id}">Modifier</button></div></div>`}).join('')||'<div class="empty-state">Aucune réservation.</div>';$$('[data-seat]').forEach(b=>b.onclick=()=>seatReservation(b.dataset.seat).catch(e=>toast(e.message,'error')));$$('[data-editres]').forEach(b=>b.onclick=()=>reservationModal(ctx.reservations.find(r=>r.id===b.dataset.editres)));const todayRows=ctx.reservations.filter(r=>r.reservation_date===today()&&!['cancelled','rejected'].includes(r.status));$('#reservationTodaySummary').innerHTML=`<div><span>Réservations</span><strong>${todayRows.length}</strong></div><div><span>Couverts prévus</span><strong>${todayRows.reduce((s,r)=>s+Number(r.party_size||0),0)}</strong></div><div><span>Déjà assis</span><strong>${todayRows.filter(r=>r.status==='seated').length}</strong></div>`}
function reservationModal(r=null){modal(`<form id="resForm"><div class="modal-title-row"><h2>${r?'Modifier':'Nouvelle'} réservation</h2><button type="button" class="icon-btn" data-close>×</button></div><div class="form-two"><label>Date<input id="rDate" type="date" required value="${r?.reservation_date||today()}"></label><label>Heure<input id="rTime" type="time" required value="${String(r?.reservation_time||'19:00').slice(0,5)}"></label></div><div class="form-two"><label>Nom<input id="rName" required value="${esc(r?.customer_name||'')}"></label><label>Personnes<input id="rParty" type="number" min="1" max="100" required value="${r?.party_size||2}"></label></div><div class="form-two"><label>Téléphone<input id="rPhone" value="${esc(r?.phone||'')}"></label><label>Courriel<input id="rEmail" type="email" value="${esc(r?.email||'')}"></label></div><label>Notes<textarea id="rNotes">${esc(r?.notes||'')}</textarea></label><button class="btn primary full">Enregistrer</button></form>`);$('#resForm').onsubmit=async e=>{e.preventDefault();try{await ensureContext();const body={restaurant_id:ctx.restaurant.id,reservation_date:$('#rDate').value,reservation_time:$('#rTime').value,party_size:Number($('#rParty').value),customer_name:$('#rName').value.trim(),phone:$('#rPhone').value.trim()||null,email:$('#rEmail').value.trim()||null,notes:$('#rNotes').value.trim()||null,status:r?.status||'confirmed',source:r?.source||'staff',updated_at:new Date().toISOString()};let customer=ctx.customers.find(c=>(body.phone&&c.phone===body.phone)||(body.email&&c.email?.toLowerCase()===body.email.toLowerCase()));if(!customer)customer=(await rest('customers',{method:'POST',body:{id:uid(),restaurant_id:ctx.restaurant.id,name:body.customer_name,phone:body.phone,email:body.email}}))[0];body.customer_id=customer.id;if(r)await rest(`reservations?id=eq.${r.id}`,{method:'PATCH',body});else await rest('reservations',{method:'POST',body:{id:uid(),...body}});$('#modal').classList.remove('show');ctx._loadedAt=0;await renderReservations();toast('Réservation enregistrée')}catch(err){toast(err.message,'error')}}}
async function seatReservation(id){await loadBusiness(true);const r=ctx.reservations.find(x=>x.id===id);const options=ctx.tables.map(t=>`<option value="${t.id}">Table ${t.number} · ${t.seats||4} places</option>`).join('');modal(`<div class="modal-title-row"><h2>Asseoir ${esc(r.customer_name)}</h2><button class="icon-btn" data-close>×</button></div><label>Table<select id="seatTable">${options}</select></label><button id="seatConfirm" class="btn primary full">Ouvrir la table dans le POS</button>`);$('#seatConfirm').onclick=async()=>{try{const table_id=$('#seatTable').value;const existing=(await rest(`orders?restaurant_id=eq.${ctx.restaurant.id}&table_id=eq.${table_id}&status=in.(open,partially_paid)&select=*&limit=1`))?.[0];if(existing)throw new Error('Cette table est déjà ouverte');const order=(await rest('orders',{method:'POST',body:{id:uid(),restaurant_id:ctx.restaurant.id,table_id,guest_count:r.party_size,status:'open',customer_id:r.customer_id,reservation_id:r.id}}))[0];await rest(`reservations?id=eq.${r.id}`,{method:'PATCH',body:{status:'seated',assigned_table_id:table_id,order_id:order.id,seated_at:new Date().toISOString(),updated_at:new Date().toISOString()}});$('#modal').classList.remove('show');toast('Table ouverte');setTimeout(()=>document.querySelector('[data-nav="tablesScreen"]')?.click(),200)}catch(e){toast(e.message,'error')}}}

async function renderCosts(){await loadBusiness(true);const month=periodBounds('month'),actual=operatingCostsFor(month),fixed=fixedForPeriod('month');$('#costSummary').innerHTML=`<div class="metric"><span>Factures / dépenses ce mois</span><strong>${money(actual)}</strong></div><div class="metric"><span>Frais fixes mensuels</span><strong>${money(fixed)}</strong></div><div class="metric"><span>Total à couvrir</span><strong>${money(actual+fixed)}</strong></div>`;$('#costList').innerHTML=ctx.costs.map(c=>`<div class="biz-row"><div><strong>${esc(c.name)}</strong><span>${esc(c.vendor||'')} · ${esc(c.category)} · ${c.incurred_on}</span></div><strong>${money(c.amount)}</strong></div>`).join('')||'<div class="empty-state">Aucune facture ou dépense ponctuelle.</div>'}
function costModal(prefill={}){modal(`<form id="costForm"><div class="modal-title-row"><h2>Enregistrer une dépense</h2><button type="button" class="icon-btn" data-close>×</button></div><label>Description<input id="cName" required value="${esc(prefill.description||prefill.vendor||'')}"></label><div class="form-two"><label>Fournisseur<input id="cVendor" value="${esc(prefill.vendor||'')}"></label><label>Date<input id="cDate" type="date" value="${prefill.document_date||today()}"></label></div><div class="form-two"><label>Total<input id="cAmount" type="number" step="0.01" min="0" required value="${prefill.total??''}"></label><label>Catégorie<select id="cCat">${['rent','utilities','inventory','payroll','insurance','software','professional','maintenance','marketing','taxes','financing','goodwill','equipment','other'].map(x=>`<option value="${x}" ${x===prefill.category?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="form-two"><label>TPS<input id="cGst" type="number" step="0.01" min="0" value="${prefill.gst??''}"></label><label>TVQ<input id="cQst" type="number" step="0.01" min="0" value="${prefill.qst??''}"></label></div><label>Référence<input id="cRef" value="${esc(prefill.invoice_reference||'')}"></label><button class="btn primary full">Enregistrer</button></form>`);$('#costForm').onsubmit=async e=>{e.preventDefault();try{await ensureContext();await rest('business_costs',{method:'POST',body:{id:uid(),restaurant_id:ctx.restaurant.id,name:$('#cName').value.trim(),vendor:$('#cVendor').value.trim()||null,incurred_on:$('#cDate').value,amount:Number($('#cAmount').value),category:$('#cCat').value,recurrence:'one_time',invoice_reference:$('#cRef').value.trim()||null,gst:Number($('#cGst').value)||null,qst:Number($('#cQst').value)||null,subtotal:prefill.subtotal??null,document_id:prefill.document_id||null}});if(prefill.document_id)await rest(`business_cost_documents?id=eq.${prefill.document_id}`,{method:'PATCH',body:{status:'accepted'}});$('#modal').classList.remove('show');ctx._loadedAt=0;await renderCosts();toast('Dépense enregistrée')}catch(err){toast(err.message,'error')}}}
async function uploadOriginal(file,path){const h=headers();delete h['Content-Type'];h['x-upsert']='false';const r=await fetch(`${CFG.supabaseUrl}/storage/v1/object/business-cost-documents/${path}`,{method:'POST',headers:h,body:file});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||'Impossible de conserver le document original')}}
async function extractDocument(file){await ensureContext();if(file.size>15*1024*1024)throw new Error('Document trop lourd (15 Mo max)');const docId=uid(),safe=(file.name||'photo.jpg').replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${ctx.restaurant.id}/${docId}/${safe}`;const doc=(await rest('business_cost_documents',{method:'POST',body:{id:docId,restaurant_id:ctx.restaurant.id,file_name:file.name||'photo.jpg',mime_type:file.type||'image/jpeg',file_size:file.size,status:'extracting',storage_path:path}}))[0];await uploadOriginal(file,path);const b64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(file)});const resp=await fetch(`${FN}/cost-document-extractor`,{method:'POST',headers:headers(),body:JSON.stringify({file_data:b64,mime_type:file.type||'image/jpeg',file_name:file.name})}),data=await resp.json().catch(()=>({}));if(!resp.ok){await rest(`business_cost_documents?id=eq.${doc.id}`,{method:'PATCH',body:{status:'failed',error_message:data.message||data.error||'Extraction impossible'}});throw new Error(data.message||'Extraction IA non configurée')};const x=data.extracted;await rest(`business_cost_documents?id=eq.${doc.id}`,{method:'PATCH',body:{status:'review',extracted_data:x,confidence:x.confidence}});costModal({...x,document_id:doc.id})}

function wire(){
  $('#newReservation')?.addEventListener('click',()=>reservationModal());
  $('#newCost')?.addEventListener('click',()=>costModal());
  $('#scanCost')?.addEventListener('click',()=>$('#costCapture').click());
  $('#costCapture')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)extractDocument(f).catch(err=>{toast(err.message,'error');costModal()});e.target.value=''});
  $$('#dashboardPeriods [data-period]').forEach(b=>b.addEventListener('click',()=>{dashboardPeriod=b.dataset.period;$$('#dashboardPeriods [data-period]').forEach(x=>x.classList.toggle('active',x===b));renderDashboard().catch(e=>toast(e.message,'error'))}));
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-nav]');if(!b)return;const id=b.dataset.nav;setTimeout(()=>activate(id).catch(err=>toast(err.message,'error')),20)});
  const observer=new MutationObserver(()=>{if($('#tablesScreen')?.classList.contains('active'))setTimeout(renderServiceSummary,30)});if($('#tablesGrid'))observer.observe($('#tablesGrid'),{childList:true,subtree:true});
}
async function activate(id){if(id==='reservationsScreen')await renderReservations();if(id==='dashboardScreen')await renderDashboard();if(id==='costsScreen')await renderCosts()}
window.addEventListener('DOMContentLoaded',wire);
