import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import net from 'node:net';import {fileURLToPath} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const PORT=Number(process.env.PORT||8787);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json'};
function json(res,code,obj){res.writeHead(code,{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type'});res.end(JSON.stringify(obj))}
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',d=>b+=d);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
function escpos(text,cut=true){const init=Buffer.from([0x1b,0x40]);const body=Buffer.from(text+'\n','utf8');const feed=Buffer.from([0x1b,0x64,0x04]);const cutter=cut?Buffer.from([0x1d,0x56,0x00]):Buffer.alloc(0);return Buffer.concat([init,body,feed,cutter])}
function tcpPrint(ip,port,data){return new Promise((resolve,reject)=>{const s=net.createConnection({host:ip,port,timeout:5000},()=>{s.write(data,()=>s.end())});s.on('close',resolve);s.on('timeout',()=>s.destroy(new Error('timeout')));s.on('error',reject)})}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'POST,OPTIONS'});return res.end()}
if(req.method==='POST'&&req.url==='/api/mev/mock'){const body=await readBody(req);return json(res,200,{status:'accepted-mock',transactionId:`MEV-MOCK-${Date.now()}`,invoiceId:body.id})}
if(req.method==='POST'&&req.url==='/print'){const b=await readBody(req);if(!b.ip||!b.text)return json(res,400,{error:'ip et text requis'});await tcpPrint(b.ip,Number(b.port||9100),escpos(String(b.text),b.cut!==false));return json(res,200,{ok:true})}
let u=req.url.split('?')[0];if(u==='/')u='/index.html';const f=path.join(__dirname,u);if(!f.startsWith(__dirname)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}catch(e){json(res,500,{error:e.message})}});server.listen(PORT,'0.0.0.0',()=>console.log(`SimplePOS: http://localhost:${PORT}`));
